export const meta = {
  name: 'lit-sweep-A',
  description: 'Literature sweep (learning theory, logic, inferentialism, justification) for the inferential-learning project',
  phases: [{ title: 'Survey', detail: 'one agent per literature strand, each writes a memo' }],
}

const ROOT = '/home/user/AI-works/inferential-learning'
const COMMON = `You are a research agent on a deep investigation. FIRST read the shared brief at ${ROOT}/research/00-brief.md carefully (it describes the user's question and the orchestrator's working hypotheses H1-H7).

Your job: produce a rigorous, technically precise literature memo on ONE strand (below), written for a mathematically/philosophically literate reader, focused on what is USEFUL for the project: precise statements of results (with hypotheses), how each maps onto our setup (learning inference rules from positive human examples + coherence + sparse world feedback + contexts), which results we could reuse or adapt as lemmas, and which known impossibility results constrain us. Also propose concrete theorem candidates for our project that this strand suggests (with a sketch of why they might be true), and flag where the orchestrator's hypotheses in the brief look wrong or need refinement.

Use WebSearch/WebFetch (load them via ToolSearch with query "select:WebSearch,WebFetch") to check citations and statements where you are unsure. Cite accurately (authors, year, title, venue); mark any citation or statement you could not verify as [unverified]. Never invent results. Prefer exact theorem statements over vague summaries.

Write the memo (markdown, typically 2500-6000 words; LaTeX-style math in $...$ is fine) to the file path given below using the Write tool. Then return the structured summary.`

const SCHEMA = {
  type: 'object',
  properties: {
    file: { type: 'string' },
    one_paragraph_summary: { type: 'string' },
    most_useful_results: { type: 'array', items: { type: 'object', properties: {
      statement: { type: 'string' }, citation: { type: 'string' }, use_for_us: { type: 'string' }, verified: { type: 'boolean' } },
      required: ['statement', 'citation', 'use_for_us', 'verified'] } },
    theorem_candidates: { type: 'array', items: { type: 'string' } },
    corrections_to_brief: { type: 'array', items: { type: 'string' } },
  },
  required: ['file', 'one_paragraph_summary', 'most_useful_results', 'theorem_candidates', 'corrections_to_brief'],
}

const STRANDS = [
  { key: 'L1-positive-data', file: 'L1-positive-data-learning.md', prompt: `STRAND L1: Learning formal languages / rule systems from positive data. Cover: Gold 1967 (identification in the limit, superfinite classes); Angluin 1980 (tell-tale characterization; pattern languages; finite thickness); Wright 1989 & Motoki-Shinohara-Wright 1991 (finite elasticity, unions of pattern languages); Shinohara 1991 & Arikawa-Shinohara-Yamamoto (elementary formal systems, length-bounded EFS learnable from positive data); Plotkin 1970/71 (least general generalization, anti-unification) and the subsumption lattice (finite ascending chains bounded by term size); ILP (Muggleton, De Raedt: learning from entailment, learning from interpretations, learning from proofs — note especially any work on learning from PROOFS / derivation trees, e.g. Passerini-Frasconi-De Raedt 'kernels on prolog proof trees' and De Raedt's 'learning from proofs'); Natarajan 1987 positive-only PAC learning & intersection-closed classes, the closure algorithm and its sample complexity (Auer-Ortner 2007; Darnstadt-Simon-Szorenyi 2016); teaching dimension / recursive teaching dimension, especially for pattern classes; learning closure systems / Horn theories (Angluin-Frazier-Pitt 1992; Frazier-Pitt 'learning from entailment'); Learning grammars from positive data with simplicity bias (MDL, Bayesian; e.g. Chater-Vitanyi 2007 'ideal learning of natural language' positive-evidence result). KEY QUESTION for us: what is the right hypothesis class for 'inference rule systems' (e.g. finite sets of rule schemas = unions of tuple-pattern languages, possibly with side conditions), and what positive-data identification / sample complexity results apply to learning the set of VALID SINGLE STEPS (not the set of theorems) — note the difference between learning from derivations vs from theorems. Also: is the class of structural (substitution-invariant) consequence relations intersection-closed, and what does that buy (minimal-closure learner = sound)?` },
  { key: 'L2-reliable', file: 'L2-reliable-selective-kwik.md', prompt: `STRAND L2: Learning with worst-case reliability: learners that may abstain but must never be wrong. Cover: Rivest & Sloan 1988 'reliable and useful learning'; KWIK (Li, Littman, Walsh 2008; Li-Littman-Walsh-Strehl 2011 'Knows what it knows'), KWIK bounds for classes, combination theorems, lower bounds, relation to mistake bounds; Szita & Szepesvari agnostic KWIK; El-Yaniv & Wiener 'perfect selective classification' (consistent selective strategy, coverage bounds via version space compression set size), Wiener-Hanneke-El-Yaniv compression technique, Hanneke disagreement coefficient and CAL active learning; Kalai-Kanade-Mansour 2012 'reliable agnostic learning'; conformal prediction with guarantees; Ville's inequality & anytime-valid inference (time-uniform guarantees against adaptive stopping, Howard-Ramdas et al., e-values, Shafer-Vovk game-theoretic probability) — including how Bayesian posterior odds give anytime-valid bounds; Bayesian 'KWIK' style results (e.g. a Bayes-mixture threshold rule that is sound when the threshold is below the prior weight of the truth; exponential lower bounds for unstructured classes). Also adversarial robustness of learned verifiers / reward models: overoptimization (Gao-Schulman-Hilton 2022 'scaling laws for reward model overoptimization'), Goodhart. KEY QUESTION for us: a learned step-validity checker V-hat will be queried by a SEARCH process (a prover) that is effectively adversarial; what learning-theoretic frameworks give guarantees that hold uniformly over arbitrary (adaptive) query sequences, what are the tight bounds on the number of abstentions/escalations-to-humans, and what structural properties of hypothesis classes (e.g. sets of rule schemas learned by anti-unification) make those bounds small? Work out (in the memo) a clean statement + proof sketch of: 'Bayesian-conservative acceptance (accept iff posterior prob of invalid < delta) is sound against arbitrary adaptive provers with probability >= 1-delta-prime when delta <= w* delta-prime' (use Ville), and the matching escalation bound and lower bound.` },
  { key: 'L3-learning-to-reason', file: 'L3-learning-to-reason-and-limit-inquiry.md', prompt: `STRAND L3: Learning-to-reason frameworks and formal learning theory of inquiry. Cover: Khardon & Roth 1997 'Learning to reason' (JACM) and follow-ups (learning to reason with a restricted view); Valiant 2000 'Robust logics' and 'knowledge infusion' (2006); Juba 2013 'Implicit learning of common sense for reasoning' and PAC-semantics, Michael & Valiant, Juba's later work on 'learning to reason with partial observability', Rader-Juba?; Garrabrant et al. 2016 'Logical induction' (criterion, properties: coherence in the limit, provability induction, calibration, self-trust), Demski 2012 prior over sentences, Hutter-Lloyd-Ng-Uther 2013 'Probabilities on sentences in an expressive logic', Gaifman 1964/2004 on probability for logical sentences; Solomonoff induction and its relevance to 'axiom induction' (cf. the user's note solomonoff axiom induction); Kevin Kelly 1996 'The logic of reliable inquiry' (decidability/verifiability/refutability in the limit characterized by Borel complexity; Sigma2/Delta2 results), Kelly-Schulte, Genin-Kelly 2017/2018 'theory choice, theory change and inductive truth-conduciveness' (Ockham efficiency), Putnam 1965 trial-and-error predicates, Gold 1965 limiting recursion, Shoenfield limit lemma, Osherson-Stob-Weinstein 'Systems that learn' & 'Mechanical learners pay a price for Bayesianism'; merging of opinions (Blackwell-Dubins 1962), Gaifman-Snir 1982 convergence to truth. KEY QUESTION for us: in a setup where an agent learns inference rules and gets (a) coherence information and (b) occasional truth-values of sentences from the world (in math: computation, e.g. Delta0 facts), what can be achieved in the limit and at what rates? E.g. which classes of sentences can the learned reasoner get right in the limit; can we make 'derives lots of correct conclusions' precise via these frameworks; what are the impossibility results (e.g. no computable learner is Sigma1-sound and complete for arithmetic; what 'in the limit' buys)? Relate logical induction's 'coherence' to the user's coherence loss.` },
  { key: 'L4-inferentialism', file: 'L4-inferentialism-and-categoricity.md', prompt: `STRAND L4: Inferentialism, proof-theoretic semantics, and the determinacy of meaning by rules. Cover: Sellars (material inference; 'Inference and meaning' 1953), Brandom (Making It Explicit 1994; Articulating Reasons 2000; incompatibility semantics in Between Saying and Doing 2008, with Aker's appendix; material incompatibility), Dummett (harmony, 'The logical basis of metaphysics', fundamental assumption), Prawitz (proof-theoretic validity), Schroeder-Heister, Gentzen ('introduction rules define meaning'); Prior 1960 'The runabout inference-ticket' (tonk) and Belnap 1962 'Tonk, plonk and plink' (conservativeness, uniqueness), Stevenson, Peregrin 2014 'Inferentialism: why rules matter'; Carnap 1943 'Formalization of logic' categoricity problem (non-normal valuations), Smiley 1996 rejection, Rumfitt 2000 'Yes and No' bilateralism, Restall 2005 'Multiple conclusions' (normative reading: Gamma |- Delta means asserting all of Gamma while denying all of Delta is out of bounds), Ripley, Garson 2013 'What logics mean', Murzi & Hjortland 2009, Raatikainen 2008, Bonnay & Westerstahl 2016 'Compositionality solves Carnap's problem' (and their later work), Shoesmith-Smiley multiple-conclusion logic; Kripke 1982 'Wittgenstein on rules and private language' (quus; skeptical solution via community), Goodman's grue, Wittgenstein on rule-following; Lewis 'naturalness/reference magnetism' as a selection principle. KEY QUESTIONS: (1) make precise the analogy 'Carnap's categoricity problem ~ Gold's theorem': positive (assertion/derivability) data underdetermines meaning; adding negative/coherence data (denial, multiple-conclusion sequents, incompatibilities) restores determinacy. State the exact known categoricity results (which connectives/quantifiers become categorical under which kind of consequence relation + which extra assumptions). (2) What does inferentialism say about which inferences are meaning-constitutive vs collateral (material) and how a learner would distinguish them? (3) tonk/harmony/conservativeness as coherence constraints on LEARNED rules for NEW vocabulary. (4) Kripkenstein as non-identifiability: what extra structure (simplicity, coherence, community) resolves it, and what would each correspond to in a learner?` },
  { key: 'L5-logic-facts', file: 'L5-logic-facts.md', prompt: `STRAND L5: Mathematical-logic facts our theory will lean on; state each precisely with references. Cover: Post-completeness of classical propositional logic (as a set of theorems closed under substitution and MP) and its failure for intuitionistic logic; structural completeness (CPC structurally complete; IPC not; admissible vs derivable rules); the lattice of structural extensions of classical consequence (Wojcicki's 'Theory of logical calculi'; Tokarz; the 'almost inconsistent' extension), Los-Suszko structural consequence, Lindenbaum's lemma; Beth definability & Craig interpolation; conservative extensions (definitional extensions are conservative; theoretical terms in empirical theories aren't — Ramsey sentences, Carnap); Godel-Rosser incompleteness and the existence of many mutually incompatible consistent r.e. extensions (e.g. PA + not-Con(PA)); Sigma1-soundness, omega-consistency, 1-consistency; reflection principles, Turing/Feferman progressions, the 'implicit commitment thesis' (Feferman 1991 'Reflecting on incompleteness'; Dean; Lingamfelter? Nogina? check), Kreisel 1967 'Informal rigour and completeness proofs' and the squeezing argument (and Smith/Halbach discussions); decidability of membership in theorems vs proofs; Shoenfield limit lemma, Delta2 = limit computable, Putnam/Gold. Also: for a fixed finite set of rule SCHEMAS, decidability of 'is this step an instance' (matching) vs undecidability of 'is this system consistent' / 'is this extension conservative' (give complexity: Pi1, Pi2, etc.). KEY QUESTION: what do these facts imply for a COHERENCE-DRIVEN learner of inference rules: in which logics does 'maximal coherent extension of the data' coincide with the target (Post-completeness), where does coherence fail to determine the target (incompleteness), what can and cannot be checked or learned in the limit, and what do reflection principles say about which NEW inferences a learner that has accepted a system is committed to (a principled source of new valid inferences beyond imitation)? Give exact statements and proof sketches for the key ones, especially the result about classical propositional logic: any substitution-closed rule/axiom not derivable in CPC trivializes it (or the precise correct version for consequence relations).` },
  { key: 'L11-justification', file: 'L11-justification-and-reflective-equilibrium.md', prompt: `STRAND L11: Epistemology of justification relevant to learned inference rules. Cover: Goodman 1955 'Fact, Fiction and Forecast' ch.3 ('rules and particular inferences alike are justified by being brought into agreement with each other' — the original reflective equilibrium about inference rules; this is essentially the user's setup), Rawls reflective equilibrium (narrow/wide), Stich 1990 'The fragmentation of reason' and Stich-Nisbett 1980 'Justification and the psychology of human reasoning' (reflective equilibrium can endorse systematic fallacies like the gambler's fallacy), L. J. Cohen 1981 'Can human irrationality be experimentally demonstrated?' (competence/performance), Wason/Kahneman-Tversky evidence on human inference errors that are systematic; coherentism (BonJour 1985), Thagard's coherence as constraint satisfaction ('Coherence in thought and action' 2000), Olsson/Bovens-Hartmann impossibility results on coherence and truth-conduciveness (coherence is NOT generally truth-conducive — state precisely); Peirce's convergence theory of truth, Reichenbach's pragmatic vindication of induction (straight rule), Putnam's 'internal realism', Dummett's anti-realism (truth as warranted assertibility); Carnap's principle of tolerance; Quine 'Two dogmas' (web of belief, revisability of logic) and Quine 'Truth by convention'; Lewis Carroll 1895 'What the tortoise said to Achilles' (rules vs premises — highly relevant to learning rules vs learning facts); Boghossian on blind reasoning and meaning-constitutive inference; 'bootstrapping'/easy knowledge for rule-circular justification (Boghossian, Dummett on justification of deduction); Haack 1976 'The justification of deduction'. KEY QUESTIONS: (1) What is the best philosophical account of 'principled justification beyond proof' that our learning setup could instantiate, and what would a THEOREM about such a setup be evidence for? (2) The Stich-vs-Cohen debate maps onto our 'systematic coherent human error' problem: what does it predict about learning from human inferences + coherence? (3) The Bovens-Hartmann/Olsson impossibility results: do they bite against a coherence loss, and what extra structure (e.g. independence of evidence sources, world feedback) escapes them? (4) Carroll's regress: what is the formal difference between a learned RULE and a learned conditional PREMISE, and why does it matter for a learner?` },
]

phase('Survey')
const results = await parallel(STRANDS.map(s => () => agent(
  `${COMMON}\n\nWrite the memo to: ${ROOT}/research/lit/${s.file}\n\n${s.prompt}`,
  { label: s.key, phase: 'Survey', schema: SCHEMA })))
return results.filter(Boolean)
