export const meta = {
  name: 'lit-sweep-B',
  description: 'Literature sweep (informal math, contexts/idealization, ML practice, physics verification, user notes)',
  phases: [{ title: 'Survey', detail: 'one agent per literature strand, each writes a memo' }],
}

const ROOT = '/home/user/AI-works/inferential-learning'
const COMMON = `You are a research agent on a deep investigation. FIRST read the shared brief at ${ROOT}/research/00-brief.md carefully (it describes the user's question and the orchestrator's working hypotheses H1-H7).

Your job: produce a rigorous, technically precise literature memo on ONE strand (below), written for a mathematically/philosophically literate reader, focused on what is USEFUL for the project: precise statements of results/claims, how each maps onto our setup (learning inference rules from positive human examples + coherence + sparse world feedback + contexts), which ideas we could reuse, and which known problems constrain us. Also propose concrete theorem candidates or design ideas for our project that this strand suggests, and flag where the orchestrator's hypotheses in the brief look wrong or need refinement.

Use WebSearch/WebFetch (load them via ToolSearch with query "select:WebSearch,WebFetch") to check citations and statements where you are unsure. Cite accurately (authors, year, title, venue); mark any citation or statement you could not verify as [unverified]. Never invent results.

Write the memo (markdown, typically 2500-6000 words) to the file path given below using the Write tool. Then return the structured summary.`

const SCHEMA = {
  type: 'object',
  properties: {
    file: { type: 'string' },
    one_paragraph_summary: { type: 'string' },
    most_useful_results: { type: 'array', items: { type: 'object', properties: {
      statement: { type: 'string' }, citation: { type: 'string' }, use_for_us: { type: 'string' }, verified: { type: 'boolean' } },
      required: ['statement', 'citation', 'use_for_us', 'verified'] } },
    theorem_candidates: { type: 'array', items: { type: 'string' } },
    corrections_to_brief: { type: 'array', items: { type: 'string' } },
  },
  required: ['file', 'one_paragraph_summary', 'most_useful_results', 'theorem_candidates', 'corrections_to_brief'],
}

const STRANDS = [
  { key: 'L6-informal-math', file: 'L6-informal-math-and-formalization-history.md', prompt: `STRAND L6: Informal mathematics, its reliability, and the history of formalization viewed as a LEARNING problem. Cover: Lakatos 'Proofs and Refutations' (monster-barring, exception-barring, lemma-incorporation, proof-generated concepts) — treat as a dynamics of concept/rule revision under counterexamples; Frege's Grundgesetze Basic Law V / naive comprehension, Russell's paradox (1902), Zermelo 1908 axiomatization and his stated methodology (axioms extracted from existing practice of set theory, restricted to avoid antinomies), Hilbert's program, Bourbaki; the de Bruijn factor (Wiedijk) as a measure of informal-to-formal expansion; Azzouni's derivation-indicator view; Avigad 2021 'Reliability of mathematical inference' (Synthese) and Avigad's 'Mathematical rigor/understanding' work; Tanswell 'A problem with the dependence of informal proofs on formal proofs'; Hamami 'Mathematical rigor and proof' (2022); Burgess 'Rigor and structure' (2015); Rav 'Why do we prove theorems?'; Thurston 'On proof and progress in mathematics' (1994); De Millo-Lipton-Perlis 1979 (social process); Kitcher 'The nature of mathematical knowledge' (mathematical practice change); Polya; Mancosu; the history of the calculus (infinitesimals; Berkeley's criticism; how mathematicians reasoned reliably with inconsistent foundations — connect to chunk & permeate); Cauchy's 'sum theorem' error and its correction (Lakatos); Euler's sloppy-but-correct series manipulations; Kreisel's informal rigour; autoformalization (Wu et al 2022 'Autoformalization with LLMs', Szegedy 2020 'A promising path towards autoformalization'). KEY QUESTIONS: (1) What would a learning setup that 'would have worked for mathematical proofs before we knew how to formalize them' have to do, judged against this history? E.g. could an MDL+coverage+coherence learner over formal systems have 'discovered' ZF from pre-1900 practice (and naive comprehension first, refuted by Russell)? What data (accepted proofs, rejected proofs, paradoxes, counterexamples) drove the actual history? (2) How did informal mathematics stay reliable without formal checking — what mechanisms (redundancy, multiple proofs, checking special cases, community scrutiny) look like coherence or world feedback? (3) What are the documented cases where accepted informal proofs were wrong, and how were they caught? Be concrete.` },
  { key: 'L7-contexts-idealization', file: 'L7-contexts-idealization-inconsistency.md', prompt: `STRAND L7: Contexts, idealization, and reasoning with inconsistent or false assumptions. Cover: McCarthy 1993 'Notes on formalizing context' (ist(c,p), lifting axioms), Guha 1991 thesis (contexts in Cyc), Buvac-Mason propositional logic of context; Brown & Priest 2004 'Chunk and permeate: a paraconsistent inference strategy. Part I: the infinitesimal calculus' and 2015 Part II (Bohr's atom); paraconsistent logics (LP, relevance logics, discussive logic of Jaskowski as 'logic of discussion with multiple participants'), preservationism (Schotch-Jennings), Vickers 2013 'Understanding inconsistent science'; AGM belief revision and counterfactual/counterpossible reasoning (Lewis, Stalnaker, Nolan, Berto); supposition (indicative/subjunctive); Norton 2012 'Approximation and idealization: why the difference matters' (idealizations as novel systems; limit systems that don't exist); Mark Wilson 2006 'Wandering Significance' (facades, patches, theory facades), Batterman ('The devil in the details', asymptotic reasoning), Strevens 2008 'Depth' (idealization as setting irrelevant factors to default values), Cartwright 'How the laws of physics lie', Weisberg 2007/2013 three kinds of idealization, Frigg & Hartmann models in science, McMullin 1985 Galilean idealization (de-idealization as justification), Laymon 1980s 'idealization and the testing of theories by experimentation' (monotonicity condition: better approximations should give better predictions — VERY relevant as a principled justification of idealization), Ramsey's view of approximations; perturbation theory / asymptotic analysis / matched asymptotic expansions as the mathematical form of 'justified idealization'; structural stability. ALSO the AI literature on automated modeling with explicit modeling assumptions: Falkenhainer & Forbus 1991 'Compositional modeling: finding the right model for the job'; Nayak 1995 'Automated modeling of physical systems' (causal approximations, adequacy); Weld 1992 'Reasoning about model accuracy'; Addanki-Cremonini-Penberthy 'graphs of models' (1991); Forbus qualitative process theory. KEY QUESTIONS: (1) Give a clean formal account of 'arguing in a context' where (a) contradictions inside hypothetical contexts are fine (reductio), (b) idealized contexts can be inconsistent with background knowledge, and (c) only 'exported' claims about the actual world are subject to coherence penalties. What existing formalism comes closest? (2) What principled criteria justify EXPORTING a conclusion from an idealized context to the world (Laymon monotonicity, de-idealization, stability/continuity in the idealization parameter, asymptotic validity)? (3) Concretely, how do these apply to 'assume air pressure is 0' type assumptions in physics problems?` },
  { key: 'L8-ml-practice', file: 'L8-ml-verifiers-consistency-practice.md', prompt: `STRAND L8: Machine-learning practice relevant to learned inference validity, coherence losses, and learned verifiers. Cover: process reward models and step-level verification (Uesato et al 2022; Lightman et al 2023 'Let's verify step by step' PRM800K; Math-Shepherd (Wang et al 2024); generative verifiers; LLM-as-judge for proofs; recent proof-grading benchmarks for informal olympiad proofs (e.g. IMO-ProofBench / 'Proof or bluff' (Petrov et al 2025)), and documented reward hacking of learned verifiers/graders); self-consistency (Wang et al 2022); consistency-based unsupervised methods: Burns et al 2022 'Discovering latent knowledge' (CCS, uses negation coherence as the training signal — note the user has notes on DLK), follow-ups and critiques (Farquhar et al 2023 'Challenges with unsupervised LLM knowledge discovery'), Fluri et al 2023 'Evaluating superhuman models with consistency checks', logical-consistency fine-tuning, 'coherence' training of LMs (e.g. Mitchell et al 2022 'Enhancing self-consistency and performance of pretrained LMs with NLI' (ConCoRD), Kassner et al BeliefBank); debate (Irving-Christiano-Amodei 2018; Brown-Cohen, Irving, Piliouras 2023 'Scalable AI safety via doubly-efficient debate'; 2025 'prover-estimator debate'; obfuscated arguments problem), prover-verifier games (Anil et al 2021; Kirchner et al 2024 'Prover-verifier games improve legibility'); neural theorem proving with formal checkers (GPT-f, Polu & Sutskever 2020; expert iteration Polu et al 2022; AlphaProof 2024; DeepSeek-Prover; Kimina), AlphaGeometry (Trinh et al 2024: symbolic deduction engine + synthetic data — learns nothing about rules, but relevant), Poesia et al 2024 'Learning formal mathematics from intrinsic motivation' (minimo), Peano (Poesia & Goodman 2023 'Peano: learning formal mathematical reasoning'), library learning by compression (DreamCoder Ellis et al 2021; LILO; Stitch) as MDL learning of rules/abstractions; STaR; autoformalization. KEY QUESTIONS: (1) What has been tried that is closest to 'learn which inferences are valid from human examples, then condition on coherence / truth feedback'? What worked, what failed, and why (especially: verifier exploitation under optimization pressure)? (2) Is there empirical evidence that coherence/consistency losses improve truthfulness or reasoning, and what are their known failure modes (e.g. CCS finding any coherent feature, not truth)? (3) What would a practical large-compute version of the user's setup look like given current practice, and where would theory help most?` },
  { key: 'L9-physics', file: 'L9-physics-solutions-verification.md', prompt: `STRAND L9: Physics olympiad solutions and how physics reasoning could be checked in a principled way. Cover: (a) the structure of olympiad solutions (read the user's notes in /home/user/kaarelh/notes/ai/verification and generation/verification of physics olympiad solutions/ including the 'example solutions' folder, and /home/user/kaarelh/notes/introspection/ files about solving physics olympiad problems, e.g. EuPhO 2025 T1); typical idealizing assumptions (point masses, massless strings, no air resistance, small angles, ideal gases, quasi-static processes, thin lenses), how official solutions justify or fail to justify them; (b) checks physicists use as coherence constraints: dimensional analysis (formally: units-of-measure type systems, Kennedy 1997/2009; Buckingham pi theorem), limiting cases, symmetry, conservation laws, order-of-magnitude/Fermi estimates, sanity checks of signs; (c) formalized physics: PhysLean/HepLean (Tooby-Smith), Isabelle/HOL physics formalizations, Lean/Coq formalizations of mechanics, 'physics in type theory', Boender et al?; Modelica/equation-based modeling; (d) AI physics problem solving and grading: OlympiadBench (He et al 2024), PhysicsEval, PHYBench (2025), UGPhysics, PhysReason, OlymMATH? (check), olympiad physics benchmarks and how answers are graded (final answer vs rubric), AI performance at IPhO 2025 (check reports), automated grading of physics derivations; (e) qualitative/compositional modeling in AI (Forbus; Falkenhainer-Forbus 1991; de Kleer & Brown) insofar as it treats modeling assumptions explicitly. KEY QUESTIONS: (1) What would a principled CHECKER for physics olympiad solutions look like if solutions are required to be written in a structured format: local idealized models (each a clear math problem), bridges between models and the actual problem (idealization/approximation steps with stated justification), and computations inside models? Which parts can be formally verified, which need learned judgment, and which can be validated by numerical simulation of less-idealized models? (2) Pick 2-3 concrete olympiad-style problems (ideally from the user's example solutions folder) and analyze their solutions into this format, identifying every idealization and every 'export' step and what would justify it. Be concrete and technically careful.` },
  { key: 'L10-user-notes', file: 'L10-user-notes-digest.md', prompt: `STRAND L10: Deep read of the user's own notes at /home/user/kaarelh/notes (a clone of github.com/kaarelh/notes), to extract everything relevant to this project, so that the final write-up engages with the user's own conceptions, open questions, and vocabulary. Use Grep/Glob/Read extensively (the repo has ~1000 files; filenames contain spaces). Prioritize: philosophy/philosophy of language/meaning and truth/*; philosophy/concepting/* (esp. 'good concepts are concepts that support inferences'); philosophy/philosophy of thinking/* (cheap inferences, why is thought propositional, gödel/*, advent of reason posts on thinking/understanding/justification); philosophy/philosophy of mathematics/*; philosophy/epistemology/*; philosophy/metaphilosophy/*; logic/*; ai/verification and generation/* (all, including physics olympiad verification and 'example solutions'); ai/learning/* (solomonoff axiom induction, function induction, circuit occam learning, NN bayes generalization); ai/DLK/*; introspection/* about physics olympiad solving; philosophy/prediction/*; 'questions.md', 'uncategorized ideas.md'. For each relevant note: path, 2-6 sentence summary of its claims/questions, and key verbatim quotes (short). Then synthesize: (1) what the user means by 'principled justification' and what they find unsatisfying about existing accounts; (2) their views on meaning (inferentialism vs model-theoretic semantics vs 'conceptions'/C-models), on verification (generation vs verification), on induction (Solomonoff, its weirdness), on contexts/idealization, on physics olympiad solution structure; (3) specific open questions the user has posed in the notes that our project could answer or partially answer; (4) vocabulary and framings we should use or avoid; (5) which of the orchestrator's hypotheses (H1-H7 in the brief) the user would likely find most/least compelling, and why, based on the notes.` },
]

phase('Survey')
const results = await parallel(STRANDS.map(s => () => agent(
  `${COMMON}\n\nWrite the memo to: ${ROOT}/research/lit/${s.file}\n\n${s.prompt}`,
  { label: s.key, phase: 'Survey', schema: SCHEMA })))
return results.filter(Boolean)
