export const meta = {
  name: 'theory-wave2',
  description: 'Second theory wave: steeper-simplicity (structure function), completeness for learned calculi, unified two-tier learner theorem',
  phases: [{ title: 'Develop', detail: 'three mathematician agents' }],
}
const ROOT = '/home/user/AI-works/inferential-learning'
const COMMON = `You are a research mathematician (learning theory, algorithmic information theory, mathematical logic, philosophy of logic) on a deep investigation. FIRST read ${ROOT}/research/00-brief.md and ${ROOT}/research/01-orchestrator-ideas.md, then ${ROOT}/research/lit/L10-user-notes-digest.md (the user's own views and open questions — the user is Kaarel; his notes are at /home/user/kaarelh/notes), then the theory developments ${ROOT}/research/theory/T1-soundness-under-search.md and T2-coherence-as-negative-data.md (these are strong; build on them, cite their theorem numbers, do not redo them). Consult other memos in ${ROOT}/research/lit/ as needed (L1 positive data, L2 reliable/KWIK, L4 inferentialism & Carnap, L5 logic facts). DEVELOP MATHEMATICS on your thread: precise definitions, theorems with FULL rigorous proofs (label sketches/conjectures as such), counterexamples/pathologies, honest assessment of depth. Use Python (Bash) for sanity checks and small simulations. Write your development (markdown, 5000-12000 words) to the file below, then return the structured summary.`
const SCHEMA = { type: 'object', properties: { file: { type: 'string' }, framework_summary: { type: 'string' },
  theorems: { type: 'array', items: { type: 'object', properties: { name: { type: 'string' }, statement: { type: 'string' }, status: { type: 'string', enum: ['proved', 'proof-sketch', 'conjecture', 'known-result-cited'] }, significance: { type: 'string' } }, required: ['name', 'statement', 'status', 'significance'] } },
  impossibility_results: { type: 'array', items: { type: 'string' } }, open_problems: { type: 'array', items: { type: 'string' } }, suggested_experiments: { type: 'array', items: { type: 'string' } } },
  required: ['file', 'framework_summary', 'theorems', 'impossibility_results', 'open_problems', 'suggested_experiments'] }
const JOBS = [
  { key: 'T5-steeper-simplicity', prompt: `Write to: ${ROOT}/research/theory/T5-steeper-simplicity-and-normativity-from-imitation.md

THREAD T5: The user's own conjecture about getting NORMS (the intended rules) rather than the teacher's systematic errors out of IMITATION, via a steeper simplicity penalty. Read his note in full: /home/user/kaarelh/notes/philosophy/philosophy of thinking/beating solomonoff induction at grokking a notion.md (especially the 'messy notes' part: function-Solomonoff with PRIVATE per-input randomness; loss = lambda*K(h) + sum of NLL with lambda > 1 scaling with N; his worked example with a 100-bit simple model and 10000-bit systematic error on a 2^-10 fraction of inputs; his convex-hull argument; his question whether there is a 'universal hypothesis' pathology in the function case or some other pathology, and whether it can be proved). Tasks:
(1) Formalize precisely (both an idealized Kolmogorov-complexity version and a finite/computable hypothesis-class version). Relate to Kolmogorov's structure function, algorithmic sufficient statistics, and Vereshchagin & Vitanyi 2004 'Kolmogorov's structure functions and model selection' (IEEE Trans IT) — including their result that structure functions can have essentially arbitrary shape (check the exact statement; mark unverified if you cannot) — and to MDL (two-part codes, Grunwald), and to the 'lambda-MDL' / tempered posteriors literature (Grunwald's safe Bayes / generalized Bayes with learning rate eta < 1, which is exactly a steeper simplicity penalty relative to likelihood!).
(2) Answer his 'universal hypothesis' question for the function case with private randomness: prove that no single hypothesis can adapt across inputs, and give the precise statement of what the per-input mixture achieves (it pays log(1/w) PER INPUT, not once).
(3) Prove a RATE-THRESHOLD theorem: under an additivity/independence condition (hypothesis = base model + independent 'components' each with description cost k_j and per-sample NLL reduction r_j, e.g. components acting on disjoint input regions), the minimizer of c*K(h) + empirical mean NLL (c = lambda/N) includes component j iff r_j/k_j > c (up to ties and O(log) terms); in the general case, the selected hypotheses as c varies trace the lower convex hull of achievable (K, L) points, so the 'good model' is selectable iff it is a vertex. Verify his example numerically.
(4) PATHOLOGIES (prove each): (a) rare valid rules (intended components with low rate) are discarded as noise — the steeper penalty cannot separate 'rare but valid' from 'systematic error' when rates are ordered wrongly; (b) cheap systematic errors (fallacies with short descriptions and high frequency, e.g. affirming the consequent, freshman's dream) have HIGH rate and are learned for any c that also learns the valid rules of similar rate; (c) the window of good c is not identifiable from imitation data: held-out human data (which contains the same systematic errors) always prefers the error-memorizing hypothesis, so cross-validation picks the wrong c; (d) any additional pathology you find (e.g. compensating errors, non-additivity, input-distribution shift).
(5) Specialize to INFERENCE RULES: hypotheses = rule calculi (schemas, as in T1), data = human steps with systematic fallacies; show precisely which fallacies the steeper penalty removes (expensive/idiosyncratic ones) and which need COHERENCE (cheap incoherent ones, via T2 Thm 6.1) and which survive everything (cheap coherent ones = alternative meanings, T2 Thm 6.4). State a clean 'division of labor' theorem: simplicity removes high-description-cost errors; coherence removes incoherent errors; world feedback removes empirically refutable ones; the residue is exactly the cheap, coherent, empirically-adequate alternatives. Also: the user's remark that '1+1=2 won't be true if you assign 1->rabbit and 2->chicken' — model 'specifying properties of the notion' (axioms/meaning postulates) as coherence constraints and show they are what rescue the cheap-fallacy case.
(6) Discuss honestly how this answers his question (where his hope is vindicated, where it fails) in his own vocabulary.` },
  { key: 'T6-completeness-for-learned-calculi', prompt: `Write to: ${ROOT}/research/theory/T6-philosophical-completeness.md

THREAD T6: The user's question (note: /home/user/kaarelh/notes/logic/a 'philosophical version' of gödel's completeness theorem.md): "'a mode of talking makes sense (is coherent) iff there is something it could be talking about' — is a generalization of the completeness theorem available that justifies this philosophical proposition more broadly?" (He also knows the caveat that coherence only yields NON-STANDARD existence, e.g. models of PA + not-Con(PA).) Develop a family of 'coherence iff existence' theorems for the kinds of objects our learner produces, with full proofs where feasible:
(1) Bilateral/position version: for a learned structural (multiple-conclusion) calculus R, coherent maximal positions [assert : deny] correspond exactly to valuations in the R-determined semantics (cf. T2 Lemma 4.1 duality: sequents are closed sets in valuation space). Make it a Stone-duality / adjunction statement (the user's friend Sam said 'completeness is an adjunction between sentences and models'; make that precise: Galois connection between sets of sequents and sets of valuations; closed elements on each side; the image = deductively closed consequence relations; give the closure operators).
(2) Probabilistic version: credence functions satisfying the user's CCS-style coherence constraints (see /home/user/kaarelh/notes/ai/DLK/ notes, e.g. logic.md: negation consistency, modus-ponens-type constraints) are exactly the mixtures of models (de Finetti / Gaifman / no-Dutch-book; for the finite-propositional case an exact polytope statement; for first-order, Gaifman's theorem). State exactly which coherence constraints are needed (the CCS-style pairwise constraints are NOT sufficient — prove it with a counterexample — and characterize what is).
(3) Context version: coherent families of context-indexed claims ist(c, phi) (contexts with local theories and bridge rules, cf. L7 memo multi-context systems) correspond to families of local models connected by bridge-compatible maps; prove a completeness theorem for a simple multi-context calculus (equilibrium semantics). This answers 'true in the context at hand: wtf is that?' (from his note verification from truth.md) with a semantics.
(4) Learned-rule version: if a rule set R is learned (and only known to be coherent on designated contexts), what existence does coherence buy? (Lindenbaum + canonical model for structural calculi: coherent => has a model in the matrix semantics (Wojcicki: every structural consequence relation is complete w.r.t. its Lindenbaum matrices/ bundles of matrices); compare with 'there is something it is talking about' and why that something may be a degenerate Lindenbaum matrix (syntactic model) rather than an intended structure — the non-standard caveat generalized: coherence buys existence of SOME model, categoricity buys the intended one. Characterize when the model is essentially unique (categoricity: Post-completeness for logic, completeness of theories, second-order categoricity) and what 'pins down' means for the user's question 'how are the natural numbers pinned down?'.
(5) Discuss: does this vindicate the user's philosophical proposition? Precisely where yes (existence of a model in every one of these generalized senses), where no (intended/standard existence requires more than coherence: categoricity, world anchoring, or a choice of semantics), and the connection to his views (coherence + 'hooking onto the world').` },
  { key: 'T7-two-tier-learner', prompt: `Write to: ${ROOT}/research/theory/T7-two-tier-coherent-inferential-learner.md

THREAD T7: A unified, end-to-end theorem for the user's setup in FORMAL mathematics, combining T1 and T2 into a single learning architecture and guarantee. Ingredients from T1/T2: cautious (version-space / Bayes-conservative with Ville) acceptance is sound against adaptive provers but receives no coherence signal (T2 Prop 2.9); bold oligarchic-halving learners get coherence signal with <= log2(1/w*) detected incoherences (T2 Thm 2.2); majority aggregation can be incoherent forever (T2 Thm 2.4); positive-data exact identification via anchors / coupon-collector (T1 Thm 5.3/5.4) and trimmed version spaces for sporadic noise (T1 Thm 6.2/6.3); systematic errors indistinguishable from rules by positive data (T1 Cor 6.5) but eliminated by coherence iff incoherent (T2 Thm 6.1); Post-completeness pins CPC (T2 Thm 3.3) and complete theories (T2 Prop 3.11); arithmetic: Popperian boldness (T2 Thm 3.10), Turing-chain impossibility (T2 Thm 3.9).
Design: a TWO-TIER learner: tier 1 = ASSERTION tier (cautious: accepts only steps accepted by all hypotheses in the trimmed version space of a 'live' class), tier 2 = CONJECTURE/SANDBOX tier (bold: an oligarchic coalition's rules are used to search for contradictions from designated contexts — a red team), with coherence refutations feeding back into the live class, plus a world-feedback channel (truth values on a decidable fragment / counterexample objects with step-level blame, as in L6 memo TC1). Prove an end-to-end theorem of the form: for any target calculus R* in a class H with finite anchors, human data with sporadic noise rate alpha below margin and systematic fallacy set F, any (adaptive) prover, (i) the assertion tier is sound at all times with prob >= 1-delta; (ii) the number of detected incoherences is <= log2(1/w(R*)) + (cost of noise); (iii) after N = O(sum over rules of 1/(pi_i rho_i) log ...) human steps and the incoherence budget is exhausted, the assertion tier equals Cl(R* union F_coh) where F_coh is the set of fallacies coherent with R* on the designated contexts (and world-adequate), i.e. it converges to the target modulo the 'Kripkensteinian residue'; (iv) specializations: for CPC and for complete decidable theories (RCF, Presburger) the residue is empty so the learner converges to exactly the target — 'a setup of the user's shape that provably works for formal math'; for arithmetic, state precisely what is and is not achieved (Popperian boldness for Pi1/Sigma1 claims; impossibility for Sigma2 and Turing chains). Be careful about the subtle points: how cautious acceptance interacts with the coalition (the assertion tier must remain sound even while the sandbox is bold), what 'coalition unanimity' means computationally, and that refutation search is only semi-decidable (state bounds relative to a bounded-depth refutation oracle and account for search cost separately, as the L8 memo recommends). Also give the minimax lower bounds showing each ingredient is necessary (drop positive data / caution / coherence / structurality / world feedback and exhibit failure). Finally, a short section translating the theorem into the user's vocabulary: what it says about 'learning which inferences are valid' and 'learning meanings'.` },
]
phase('Develop')
const res = await parallel(JOBS.map(j => () => agent(`${COMMON}\n\n${j.prompt}`, { label: j.key, phase: 'Develop', schema: SCHEMA })))
return res.filter(Boolean)
