# T7 round-2 repair check (author): the two two-point rare-tag bounds of T7.
#
#  (A) Thm 5.5 (rare refuter).  The rare tag mu occurs only in the scenario where accepting s is UNSOUND.
#      Claim: if Pr_1(accept s at t) <= delta then Pr_2(accept s at t) <= delta*(1-pi)^(-t)  (capped at 1).
#  (B) Thm 6.6(e) floor remark (corrected in round 2).  The rare tag Con(T_{k-1}) occurs only in the
#      scenario T_k where accepting |-Con(T_{k-1}) is SOUND.
#      Claim: if Pr_{k-1}(accept at t) <= delta then Pr_k(accept at t) <= 1-(1-delta)*(1-pi)^t.
#      The round-1 text claimed instead that Pr_k >= 1-delta' needs t >= ln((1-delta')/delta)/ln(1/(1-pi));
#      we exhibit parameters where the optimal learner beats that.
#  (C) Practice-following escalation violates (OE): with one escalated mu-instance, whose answer is
#      1[q in R^P], Thm 5.5's bound fails at t=1.
#
# Method.  Under (OE) every non-sample input is generated by scenario-independent kernels, so the acceptance
# probability at time t is phi(x) in [0,1] for x = the tag sequence of the first t samples (per-tag instance
# laws coincide, so tags are a sufficient statistic).  We maximise the 'good' acceptance probability over all
# phi subject to the 'bad' acceptance probability <= delta: a linear programme over all tag sequences
# (Neyman-Pearson), solved with scipy's linprog, and compare with the closed forms.
import itertools, math
import numpy as np
from scipy.optimize import linprog

def optimum(P_bad, P_good, tags, t, delta):
    seqs = list(itertools.product(tags, repeat=t))
    pb = np.array([math.prod(P_bad.get(a, 0.0) for a in x) for x in seqs])
    pg = np.array([math.prod(P_good.get(a, 0.0) for a in x) for x in seqs])
    res = linprog(-pg, A_ub=[pb], b_ub=[delta], bounds=[(0, 1)] * len(seqs), method="highs")
    assert res.status == 0
    return -res.fun

fails = 0
# (A) Thm 5.5: scenario 1 (bad: accepting s is unsound) has tags s,t,m with (1-pi)q_s,(1-pi)q_t,pi;
#     scenario 2 (good) has tags s,t with q_s,q_t.
for pi in (0.1, 0.3, 0.5):
    for qs in (0.3, 0.5):
        for delta in (0.0, 0.01, 0.2):
            for t in range(1, 7):
                P1 = {'s': (1 - pi) * qs, 't': (1 - pi) * (1 - qs), 'm': pi}
                P2 = {'s': qs, 't': 1 - qs}
                opt = optimum(P1, P2, ['s', 't', 'm'], t, delta)
                closed = min(1.0, delta * (1 - pi) ** (-t))
                if abs(opt - closed) > 1e-7:
                    fails += 1; print('A mismatch', pi, qs, delta, t, opt, closed)
print('(A) Thm 5.5 closed form min(1, delta(1-pi)^-t) vs LP optimum: mismatches =', fails)

# (B) Thm 6.6(e): T_{k-1} (bad: accepting |-Con is unsound for the target calculus) has tags s,t with q;
#     T_k (good) has tags s,t,c with (1-pi)q, pi.
failsB = 0
for pi in (0.1, 0.3, 0.5):
    for qs in (0.3, 0.5):
        for delta in (0.0, 0.01, 0.2):
            for t in range(1, 7):
                Pkm1 = {'s': qs, 't': 1 - qs}
                Pk = {'s': (1 - pi) * qs, 't': (1 - pi) * (1 - qs), 'c': pi}
                opt = optimum(Pkm1, Pk, ['s', 't', 'c'], t, delta)
                closed = 1 - (1 - delta) * (1 - pi) ** t
                if abs(opt - closed) > 1e-7:
                    failsB += 1; print('B mismatch', pi, qs, delta, t, opt, closed)
print('(B) floor remark closed form 1-(1-delta)(1-pi)^t vs LP optimum: mismatches =', failsB)

# Round-1 bound is false: delta tiny, delta'=0.1, pi=1/2.
pi, delta, deltap = 0.5, 1e-6, 0.1
old = math.log((1 - deltap) / delta) / math.log(1 / (1 - pi))
new = math.log((1 - delta) / deltap) / math.log(1 / (1 - pi))
t = 4
opt = optimum({'s': 0.5, 't': 0.5}, {'s': 0.25, 't': 0.25, 'c': 0.5}, ['s', 't', 'c'], t, delta)
print(f'(B) pi={pi}, delta={delta}, delta\'={deltap}: round-1 bound t >= {old:.2f}; corrected bound t >= {new:.2f};'
      f' optimal learner at t={t} accepts under T_k with prob {opt:.4f} >= 1-delta\' = {1-deltap}')
print('    -> round-1 bound violated:', opt >= 1 - deltap and t < old, '; corrected bound respected:', t >= new)

# (C) Practice-following escalation: add one observation y = answer to an escalated mu-instance outside
#     R_{sigma,tau}: y=1 in scenario 1 (mu in practice), y=0 in scenario 2.  With delta = 0 the learner
#     'accept s iff y=0' has Pr_1 = 0 and Pr_2 = 1 at t=1, while Thm 5.5 would give <= 0.
pi = 0.3
seqs = [(a, y) for a in ['s', 't', 'm'] for y in (0, 1)]
P1 = {('s', 1): 0.35 * (1 - pi), ('t', 1): 0.65 * (1 - pi), ('m', 1): pi}
P2 = {('s', 0): 0.35, ('t', 0): 0.65}
pb = np.array([P1.get(x, 0) for x in seqs]); pg = np.array([P2.get(x, 0) for x in seqs])
res = linprog(-pg, A_ub=[pb], b_ub=[0.0], bounds=[(0, 1)] * len(seqs), method='highs')
print(f'(C) with practice-following escalation, delta=0, t=1: optimal Pr_2(accept s) = {-res.fun:.3f}'
      f' (Thm 5.5 under (OE) would cap it at 0)')
print('ALL OK' if fails == 0 and failsB == 0 else 'FAILURES')
