# unit checks of the refuters on hand-verified examples (true sentences must never be refuted)
import sys; sys.path.insert(0,'/home/user/AI-works/axiom-schemas/research/tracks/untagged/code')
from dtlib import *
from refuters import *
X=H(0)
print('Ind(0+x=0) [true] refuted?', refute_arith(Ind(eq(add(Z,X),Z))))
J0star = IMP(AND(eq(add(Z,Z),Z), ALL(IMP(eq(add(Z,V(0)),Z), eq(add(Z,S(V(0))),S(Z))))), ALL(eq(add(Z,V(0)),Z)))
print('J*_0 [false; unrefutable by Delta0+logic, R1] refuted?', refute_arith(J0star))
s2 = IMP(AND(eq(Z,Z), ALL(IMP(eq(S(V(0)),V(0)), eq(S(S(V(0))),S(V(0)))))), ALL(eq(S(V(0)),V(0))))
print('(0=0 & Ax(Sx=x -> SSx=Sx)) -> Ax Sx=x [false] refuted?', refute_arith(s2))
print('closure a1+0=S0 [false] refuted?', refute_arith(eq(add(P('a1'),Z),S(Z))))
print('closure a1+0=a1 [true] refuted?', refute_arith(eq(add(P('a1'),Z),P('a1'))))
print('Q7 [true] refuted?', refute_arith(IMP(NOT(eq(P('a1'),Z)), EX(eq(P('a1'),S(V(0)))))))
russell = EX(ALL(IFF(mem(V(0),V(1)), NOT(mem(V(0),V(0))))))
print('Russell instance logic-unsat?', logic_unsat([russell]))
univ = EX(ALL(IMP(eq(V(0),V(0)), mem(V(0),V(1)))))
sep = ALL(EX(ALL(IFF(mem(V(0),V(1)), AND(mem(V(0),V(2)), NOT(mem(V(0),V(0))))))))
print('universal set alone logic-unsat?', logic_unsat([univ]), '; with designated Sep instance:', logic_unsat([univ, sep]),
      '; with forall x not x in x:', logic_unsat([univ, ALL(NOT(mem(V(0),V(0))))]))
print('HF refute Ax Ay (x in y -> y in x) [false]:', refute_hf(ALL(ALL(IMP(mem(V(1),V(0)), mem(V(0),V(1)))))))
print('HF refute Ax not x in x [true]:', refute_hf(ALL(NOT(mem(V(0),V(0))))))
print('HF refute pairing closure [true]:', refute_hf(EX(AND(mem(P('a1'),V(0)),mem(P('a2'),V(0))))))
print('HF refute Ax Ey (y in x) [false, x=empty]:', refute_hf(ALL(EX(mem(V(0),V(1))))))
