export const meta = {
  name: 'lean-formalize-core',
  description: 'Lean 4 + Mathlib formalization of core discrete theorems of the inferential-learning project',
  phases: [
    { title: 'Foundation', detail: 'propositional syntax/semantics, substitution, closure operators, step systems' },
    { title: 'Modules', detail: 'one agent per theorem module' },
    { title: 'Integrate', detail: 'full build, axiom audit, README' },
  ],
}
const ROOT = '/home/user/AI-works/inferential-learning'
const LEAN = ROOT + '/lean'
const ENV = `Lean project: ${LEAN} (lakefile.toml requires Mathlib v4.32.0; toolchain leanprover/lean4:v4.32.0 is installed; put $HOME/.elan/bin on PATH: export PATH=$HOME/.elan/bin:$PATH). Mathlib cannot be downloaded from the cache (network-blocked), so ONLY the Mathlib modules transitively imported by ${LEAN}/InfLearn/Prelude.lean are built (Finset/Fintype/Set.Finite/Order.Closure/CompleteLattice/Real.Basic/Analysis.SpecialFunctions.Log.Basic/linarith/positivity/fin_cases/Mathlib.Tactic.Common and their dependencies). Do NOT import other Mathlib modules (they are not compiled and building them would take hours); import InfLearn.Prelude (and the project's own modules) instead. RULES: no 'sorry', no 'axiom' declarations, no 'native_decide' unless unavoidable (prefer 'decide'); keep definitions faithful to the paper statements. If a full statement is out of reach, prove the strongest honest special case and document precisely what was proved vs the paper statement. Theory sources: ${ROOT}/research/theory/T1-...T7-*.md (each has numbered theorems; some files have a '## Verification log' appended with corrections — honor those).`

const FOUND_SCHEMA = { type: 'object', properties: { files: { type: 'array', items: { type: 'string' } }, api: { type: 'string' }, build_ok: { type: 'boolean' } }, required: ['files', 'api', 'build_ok'] }
const MOD_SCHEMA = { type: 'object', properties: { file: { type: 'string' }, theorems: { type: 'array', items: { type: 'object', properties: { lean_name: { type: 'string' }, paper_ref: { type: 'string' }, statement_summary: { type: 'string' }, faithful: { type: 'string', enum: ['exact', 'special-case', 'weaker', 'different'] }, note: { type: 'string' } }, required: ['lean_name', 'paper_ref', 'statement_summary', 'faithful', 'note'] } }, compiles: { type: 'boolean' }, remaining_gaps: { type: 'array', items: { type: 'string' } } }, required: ['file', 'theorems', 'compiles', 'remaining_gaps'] }

phase('Foundation')
const found = await agent(`${ENV}

TASK: write the shared foundation (other agents will build on it in parallel, so make the API clean and documented):
1. ${LEAN}/InfLearn/Prop/Basic.lean: propositional formulas over atoms indexed by Nat with constructors for bot, top (or define them), not, and, or, imp; evaluation under valuations (Nat -> Bool or Prop-valued); tautology; semantic consequence relation SemCons (X : Set Formula) (phi : Formula) : Prop; substitutions (Nat -> Formula) and their action; the key lemma eval (subst s phi) v = eval phi (fun n => eval (s n) v); a structural closure operator notion: use Mathlib's ClosureOperator (Set Formula) or a lightweight structure ConsOp with fields (extensive, monotone, idempotent) and a predicate Structural C := forall s X, (subst s) '' (C X) ⊆ C ((subst s) '' X); the classical consequence operator Cn2 X := {phi | SemCons X phi} packaged as such an operator with proofs; the trivial operator; Finitary predicate (optional).
2. ${LEAN}/InfLearn/Steps.lean: abstract step systems for T1: a step = (premises : Finset J or List J, conclusion : J) over an arbitrary type J of judgments; a rule set A : Set Step; derivability closure Cl A B (inductive: members of B, and conclusions of steps in A whose premises are derivable); Sound R := {(P, j) | j ∈ Cl R P} (or the paper's Sound(R*)); basic lemmas (monotonicity in A and B, closure property).
3. Update ${LEAN}/InfLearn.lean to import these. Build them: cd ${LEAN} && lake build InfLearn.Prop.Basic InfLearn.Steps (this compiles only these two project files; Mathlib deps are already built). Make sure it succeeds.
Return the API summary (names and signatures) that module agents will need.`, { label: 'foundation', phase: 'Foundation', schema: FOUND_SCHEMA })

const API = found ? found.api : '(read the foundation files)'
const MODCOMMON = `${ENV}

The shared foundation exists: ${LEAN}/InfLearn/Prop/Basic.lean and ${LEAN}/InfLearn/Steps.lean (already compiled). API summary from its author:
${API}

You own exactly ONE new file (named below). Do not edit other files (if you need extra general lemmas, put them in your own file). Check your file with: cd ${LEAN} && lake env lean InfLearn/<YourFile>.lean  (do NOT run 'lake build' — other agents are working concurrently; the integrator will build everything). Your file may import Mathlib modules only via InfLearn.Prelude, plus InfLearn.Prop.Basic / InfLearn.Steps. At the end of your file add '#print axioms' lines for each main theorem (they should show only propext, Classical.choice, Quot.sound). Then return the structured summary mapping each Lean theorem to its paper reference and stating how faithful it is.`

const MODULES = [
  { key: 'post-completeness', file: 'InfLearn/PostCompleteness.lean', task: `Formalize T2 Theorem 3.1 (structural Post-completeness of classical consequence): every structural consequence operator C (extensive, monotone, idempotent, structural) with Cn2 X ⊆ C X for all X satisfies C = Cn2 or C is trivial (C X = univ for all X). The proof: if X ⊢_C phi but X ⊭ phi, pick a valuation v with v(X) true and v(phi) false; substitute each atom by a closed-style formula (e.g. top/bot, or p->p / not(p->p) if no constants) according to v; then sigma X are tautologies and sigma phi is unsatisfiable; by structurality sigma X ⊢_C sigma phi; tautologies are in C(∅) (Cn2 ∅ ⊆ C ∅); so by monotonicity+idempotence sigma phi ∈ C ∅; an unsatisfiable formula Cn2-entails everything, so C ∅ = univ, hence C X = univ for all X. Then formalize T2 Theorem 3.3(a)-style corollary: 'coherence pins CPC': if C is structural, extends Cn2, and there is one designated context A that is classically satisfiable with C A ≠ univ (coherence datum), then C = Cn2. Also formalize T7 Lemma 6.1 (a pure propositional schema/step [premises ⊢ conclusion] is classically invalid iff some top/bot substitution for its atoms gives a closed instance with true premises and false conclusion).` },
  { key: 'carnap', file: 'InfLearn/Carnap.lean', task: `Formalize T2 Lemma 4.1 (single-conclusion part) and Theorem 4.2 (Carnap's problem in learning form): for a set V of valuations (functions Formula -> Bool, NOT necessarily truth-functional), define single-conclusion consequence X ⊨_V phi := forall v ∈ V, (forall psi ∈ X, v psi) -> v phi, and multiple-conclusion consequence X ⊨m_V Y := forall v ∈ V, (forall psi ∈ X, v psi) -> exists chi ∈ Y, v chi. Prove: (1) ⊨_V depends only on the intersection-closure of V: if V ⊆ W ⊆ intClosure V (where w ∈ intClosure V iff w's true-set is the intersection of the true-sets of some subfamily of V, including the empty subfamily giving the all-true valuation), then ⊨_V = ⊨_W. (2) Consequently the set BV of Boolean (truth-functional classical) valuations and W = BV ∪ {v_top} (all-true valuation) and W = BV ∪ {v_T} for v_T the characteristic function of the set of classical tautologies have the same single-conclusion consequence relation (Carnap's non-normal valuations), while the multiple-conclusion relation distinguishes them: exhibit a multiple-conclusion sequent (e.g. ∅ ⊨m {p, not p}) valid for BV and invalid for W. (3) If feasible, the denial-rank style statement or T2 Theorem 4.4 (bilateral tell-tale) — optional.` },
  { key: 'step-soundness', file: 'InfLearn/StepSoundness.lean', task: `Formalize from T1: (1) Lemma 1.1: for accepted step set A and target rule set R: (forall B, Cl A B ⊆ Cl R B) iff A ⊆ Sound(R) (the set of steps (P, j) with j ∈ Cl R P). (2) Theorem 3.1(a): the version-space verifier is sound: if R* ∈ H and all hypotheses are step sets, accepting exactly the steps in the intersection of all h ∈ VS (VS = hypotheses containing the positive data) never accepts a step outside R*; and (b) optimality in the deterministic form: any acceptance set that is sound for every hypothesis in VS (i.e. contained in each h ∈ VS's sound set) is contained in the intersection — state for the step-set closure version. (3) Theorem 2.1 ('tonk beyond the horizon') in a concrete propositional natural-deduction-like calculus over Formula: give a sound target rule set R* (containing at least or-introduction/top-introduction as used by the paper's construction) and the single invalid schema T_j = {A or top^j ⊢ A}, and prove R* ∪ T_j derives every formula from the empty context; and that the instances of T_j for distinct j are disjoint sets (so any probability distribution on steps gives T_j mass -> 0: you may prove this measure-free form: for any summable weight function on steps, sum over T_j instances tends to 0, or simply the disjointness + the trivialization). Read T1 §1-3 for exact definitions.` },
  { key: 'coherence-games', file: 'InfLearn/CoherenceGames.lean', task: `Formalize: (1) T2 Theorem 2.4 (doctrinal paradox for verifier ensembles): three classical theories T1={p,q}, T2={p,not q}, T3={not p, q}; each is satisfiable (coherent); the five-step argument (⊢p, ⊢q, p,q ⊢ p∧q, ⊢ not(p∧q), p∧q, not(p∧q) ⊢ bot) has each step accepted by a majority (≥2 of 3) of the hypotheses h_i = Cn2(T_i) (step (P,c) accepted by h_i iff c ∈ Cn2(T_i ∪ P)), derives bot from the empty context, and yet every individual step is accepted by at least one... and the argument refutes none of the h_i (no h_i accepts all five steps). (2) An abstract halving/weight bound (T2 Theorem 2.2 core and T4 Theorem 4.3 core): a sequence of positive weights W_0 ≥ W_1 ≥ ... with W_{t+1} ≤ W_t/2 at each 'detection' step and W_t ≥ w* > 0 throughout implies the number of detections k satisfies 2^k ≤ W_0/w* (so k ≤ log2(W_0/w*)); and the oligarchic-halving lemma in finite form: with a finite weighted version space and an accepted set equal to the intersection of a coalition of weight ≥ half, any detected bag (subset of accepted steps that is refuted) eliminates every coalition member, hence at least half the weight, and never eliminates a hypothesis that does not contain the bag (in particular the target if the target is clean). Use Finset sums over a Fintype of hypotheses with real weights.` },
  { key: 'blame', file: 'InfLearn/Blame.lean', task: `Formalize T7 Lemma 2.3 (Reiter hitting-set duality) for a finite universe U (Finset over a DecidableEq type) and an upward-closed family K of 'conflicts' (a set S is clean iff it contains no member of K): (a) every maximal clean subset is the complement of a minimal transversal (hitting set) of the minimal conflicts, and conversely; (b) an element lies in some minimal transversal iff it lies in some minimal conflict; hence the intersection of all maximal clean sets equals U minus the union of the minimal conflicts, and that set is clean. Also formalize T4 Lemma 4.1 (descent along false lines) in an abstract proof-DAG form: given a finite derivation tree where each node is an inference whose conclusion is false under a valuation and whose leaves (premises) are true, there is a node with all premises true and conclusion false (found by walking back along false premises); state with an inductive tree type.` },
  { key: 'rate-threshold', file: 'InfLearn/RateThreshold.lean', task: `Formalize T5 Theorem 3.2 (separable components: rate threshold) and the convex-hull selection lemma in finite form, plus the counterexample to the user's vertex conjecture (T4 Prop 7.3 / T5 rate inversion): (1) for finitely many independent binary components j with description cost k_j > 0 and risk reduction r_j ≥ 0, the objective J(S) = c * (base + sum_{j∈S} k_j) + (R0 - sum_{j∈S} r_j) over subsets S is minimized exactly by S* = {j | r_j > c k_j} (unique when no ties r_j = c k_j); (2) corollary: a set of 'valid' components V is selectable by some c > 0 iff min_{j∈V} r_j/k_j > max_{j∉V} r_j/k_j (rates separated); (3) a concrete instance: a frequent short fallacy (high rate) and a rare long valid rule (low rate) such that no c selects exactly the valid set (prove for all c > 0 the minimizer is not exactly the valid set). Use Real and Finset sums.` },
  { key: 'contexts', file: 'InfLearn/Contexts.lean', task: `Formalize two small but central results about contexts: (1) T3 Theorem 2.1 (no truth-functional eternal reading) in a propositional toy: worlds = valuations; an idealized context c with stipulation S false at the actual world w0; in-context truth of phi defined as truth at a designated 'idealized world' w_c (or in all worlds of a model class) where S holds; show no function f : Bool -> Bool -> Bool such that for all phi, [phi holds in c] = f(eval S w0, eval phi w0) — i.e. in-context truth is not truth-functional in the actual truth values of stipulation and claim (construct two formulas with equal actual truth values but different in-context truth). (2) T3 Theorem 1.9(c) (reductio hygiene): the imported fragment K = {A -> q, not A -> q, not q} is classically inconsistent, yet each of the reductios 'K ⊢ not A' and 'K ⊢ A' uses a satisfiable 2-premise subset (e.g. {A->q, not q} is satisfiable and together with supposition A is unsatisfiable; {not A -> q, not q} satisfiable, and with supposition not A unsatisfiable). (3) T2 Proposition 7.1 (mis-designated contexts force sub-classicality), in the form: if a structural C extends Cn2 then every designated context containing alpha and not alpha has C-closure = univ; hence a structural C that is coherent on a classically inconsistent designated context cannot extend Cn2. (You may import InfLearn.PostCompleteness? NO — modules are developed concurrently; re-prove what you need locally.)` },
]

phase('Modules')
const mods = await parallel(MODULES.map(m => () => agent(`${MODCOMMON}\n\nYOUR FILE: ${LEAN}/${m.file}\nTASK: ${m.task}`, { label: `lean:${m.key}`, phase: 'Modules', schema: MOD_SCHEMA })))

phase('Integrate')
const integ = await agent(`${ENV}

Module agents have written files under ${LEAN}/InfLearn/ (PostCompleteness, Carnap, StepSoundness, CoherenceGames, Blame, RateThreshold, Contexts) on top of Prop/Basic and Steps. Their summaries:
${JSON.stringify(mods.filter(Boolean), null, 1)}

TASK (integrator): (1) add all modules to ${LEAN}/InfLearn.lean and run 'cd ${LEAN} && lake build'. Fix any errors (including name clashes) minimally, without weakening theorems. (2) Grep for 'sorry', 'axiom', 'native_decide' and report. (3) Create ${LEAN}/Audit.lean that imports InfLearn and runs '#print axioms' for every main theorem, plus a lean_lib Audit target in lakefile.toml; build it and capture the output to ${LEAN}/audit-output.txt. (4) Write ${LEAN}/README.md: build instructions (including the note that Mathlib's cache was unavailable so the needed Mathlib subset was compiled from source; 'lake exe cache get' works where the cache is reachable), and a table mapping each paper theorem (T1..T7 numbering, and later paper numbering) to its Lean name, file, and faithfulness (exact / special case / weaker), with honest notes on what is not formalized. Return a structured summary.`, { label: 'lean:integrate', phase: 'Integrate', schema: MOD_SCHEMA })
return { found, mods, integ }
