export const meta = {
  name: 'lean-formalize-wave2',
  description: 'Lean wave 2: more verified theorems of the inferential-learning project',
  phases: [
    { title: 'Foundation', detail: 'propositional syntax/semantics, substitution, closure operators, step systems' },
    { title: 'Modules', detail: 'one agent per theorem module' },
    { title: 'Integrate', detail: 'full build, axiom audit, README' },
  ],
}
const ROOT = '/home/user/AI-works/inferential-learning'
const LEAN = ROOT + '/lean'
const ENV = `Lean project: ${LEAN} (lakefile.toml requires Mathlib v4.32.0; toolchain leanprover/lean4:v4.32.0 is installed; put $HOME/.elan/bin on PATH: export PATH=$HOME/.elan/bin:$PATH). Mathlib cannot be downloaded from the cache (network-blocked), so ONLY the Mathlib modules transitively imported by ${LEAN}/InfLearn/Prelude.lean are built (Finset/Fintype/Set.Finite/Order.Closure/CompleteLattice/Real.Basic/Analysis.SpecialFunctions.Log.Basic/linarith/positivity/fin_cases/Mathlib.Tactic.Common and their dependencies). Do NOT import other Mathlib modules (they are not compiled and building them would take hours); import InfLearn.Prelude (and the project's own modules) instead. RULES: no 'sorry', no 'axiom' declarations, no 'native_decide' unless unavoidable (prefer 'decide'); keep definitions faithful to the paper statements. If a full statement is out of reach, prove the strongest honest special case and document precisely what was proved vs the paper statement. Theory sources: ${ROOT}/research/theory/T1-...T7-*.md (each has numbered theorems; some files have a '## Verification log' appended with corrections — honor those).`

const FOUND_SCHEMA = { type: 'object', properties: { files: { type: 'array', items: { type: 'string' } }, api: { type: 'string' }, build_ok: { type: 'boolean' } }, required: ['files', 'api', 'build_ok'] }
const MOD_SCHEMA = { type: 'object', properties: { file: { type: 'string' }, theorems: { type: 'array', items: { type: 'object', properties: { lean_name: { type: 'string' }, paper_ref: { type: 'string' }, statement_summary: { type: 'string' }, faithful: { type: 'string', enum: ['exact', 'special-case', 'weaker', 'different'] }, note: { type: 'string' } }, required: ['lean_name', 'paper_ref', 'statement_summary', 'faithful', 'note'] } }, compiles: { type: 'boolean' }, remaining_gaps: { type: 'array', items: { type: 'string' } } }, required: ['file', 'theorems', 'compiles', 'remaining_gaps'] }

const API_PLACEHOLDER = 0
const found = { api: 'The foundation and seven modules already exist and build: InfLearn/ConsOp.lean, Prop/Basic.lean, Steps.lean, PostCompleteness.lean, Carnap.lean, StepSoundness.lean, CoherenceGames.lean, Blame.lean, RateThreshold.lean, Contexts.lean. READ the files you need (and ' + LEAN + '/README.md) for the API; reuse their definitions (e.g. Carnap.lean has valuations as Formula -> Bool, closure, mrel; CoherenceGames has finite weighted hypothesis classes; StepSoundness has the verifier protocol).' }
const API = found.api
const MODCOMMON = `${ENV}

The shared foundation exists: ${LEAN}/InfLearn/Prop/Basic.lean and ${LEAN}/InfLearn/Steps.lean (already compiled). API summary from its author:
${API}

You own exactly ONE new file (named below). Do not edit other files (if you need extra general lemmas, put them in your own file). Check your file with: cd ${LEAN} && lake env lean InfLearn/<YourFile>.lean  (do NOT run 'lake build' — other agents are working concurrently; the integrator will build everything). Your file may import Mathlib modules only via InfLearn.Prelude, plus InfLearn.Prop.Basic / InfLearn.Steps. At the end of your file add '#print axioms' lines for each main theorem (they should show only propext, Classical.choice, Quot.sound). Then return the structured summary mapping each Lean theorem to its paper reference and stating how faithful it is.`

const MODULES = [
  { key: 'bilateral', file: 'InfLearn/Bilateral.lean', task: `Formalize T6 Thm 2.2 / Cor 2.3 (bilateral Lindenbaum; strong bilateral completeness): define a Scott relation on Formula (a relation between finite sets of formulas Gamma |- Delta closed under overlap (Gamma ∩ Delta ≠ ∅ implies Gamma |- Delta), weakening, and cut (Gamma |- Delta, phi and phi, Gamma |- Delta imply Gamma |- Delta), possibly in the set-based compactness form used in T6); prove every coherent position [X : Y] (no finite Gamma ⊆ X, Delta ⊆ Y with Gamma |- Delta) extends to a maximal coherent position, which is (the true/false sets of) a valuation v that satisfies every sequent of the relation (admissible valuation); conclude Th(Mod(S)) = generated Scott relation for any set S of sequents (Cor 2.3). Also, if possible, T6 Thm 2.6 (structural Scott relations correspond to substitution-invariant valuation sets). Read T6 §2 in ${ROOT}/research/theory/T6-philosophical-completeness.md (use its repaired statements).` },
  { key: 'specker', file: 'InfLearn/Specker.lean', task: `Formalize T6 Thm 3.4 (no bounded-arity coherence constraints suffice) in its explicit form: for k ≥ 3 atoms A_1..A_k, the credence P_k with P_k(A_i) = 1/(k-1) and P_k(A_i ∧ A_j) = 0 (i ≠ j) is (a) GLOBALLY incoherent: there is no probability distribution on the 2^k Boolean worlds (functions Fin k -> Bool) with those marginals; and (b) coherent on every sub-agenda mentioning at most k-1 of the atoms: for every set S of atoms with |S| ≤ k-1 there is a probability distribution on worlds matching P_k on all A_i (i ∈ S) and all A_i ∧ A_j (i,j ∈ S). Use finite sums over Fintype worlds with real weights (nonnegative, summing to 1). Also state the k = 3 instance (Specker's parable) as a corollary. Read T6 §3 for the statement.` },
  { key: 'paradox-lb', file: 'InfLearn/ParadoxLowerBound.lean', task: `Formalize T4 Thm 4.4(b),(c) lower bounds (paradox feedback can cost |H|-1 corrections while object feedback costs 1): define the online correction game with bag feedback of size ≤ r over a finite hypothesis class (hypotheses = sets of steps / items), and the single-culprit class; prove (b) for the single-culprit class an adversary forces min(r, |H|-1) corrections on any deterministic learner, while object (singleton) feedback needs at most 1; and (c) the chain-paradox version (sorites-shaped: a designated context {q_0, not q_n} with a chain q_0 => q_1 => ... => q_n where only full-chain bags are available) forces |H|-1 corrections. Read T4 §4 (${ROOT}/research/theory/T4-informal-math-latent-formalization.md, repaired statements) for exact definitions; formalize the deterministic-learner version. Reuse CoherenceGames.lean definitions if convenient.` },
  { key: 'unstructured', file: 'InfLearn/Unstructured.lean', task: `Formalize T1 Thm 3.9 (unstructured classes: escalation cost |H|-1, attained by the co-singleton class) and the lower-bound half of T1 Thm 3.2 (any deterministic 0-sound verifier must escalate or reject every step of an elastic chain inside the target) in the deterministic protocol model of StepSoundness.lean (reuse its definitions of verifier, prover, run, DetSound). Concretely: (1) upper bound: for finite H the VS verifier escalates at most |H|-1 times against an honest prover; (2) lower bound: for the co-singleton class {U \\ {u} : u ∈ U} with |U| = n there is an honest prover forcing every deterministic 0-sound verifier to escalate (or reject valid steps) n-1 times... (state precisely; read T1 §3 repaired statements in ${ROOT}/research/theory/T1-soundness-under-search.md).` },
  { key: 'export', file: 'InfLearn/Export.lean', task: `Formalize two T3 results over the reals: (1) no free export from finitely many samples (T3 Thm 3.3(d) / Lemma 3.2 in its simplest form): for any finite set S of sample parameters, any lambda* not in S, any function Q : R -> R and any epsilon > 0, there is Q' = Q + A * prod_{s in S} (lambda - s) agreeing with Q on S with |Q'(lambda*) - Q(lambda*)| > epsilon (so no sound finite-tolerance export rule can depend only on the samples, if the family class is closed under adding such polynomial multiples) — state the impossibility theorem for 'export rules' as functions of the sample values; (2) the conservative Lipschitz certifier is sound (T3 Thm 4.5, soundness half): if e : R^d (or R, then generalize if easy) -> R is L-Lipschitz w.r.t. sup norm (or |.| in 1-D) and queried values satisfy |e(x_i) - ehat_i| ≤ eta, then any x with ehat_i + eta + L * dist(x, x_i) ≤ tau for some i satisfies e(x) ≤ tau; and the matching query lower bound in 1-D if feasible (any deterministic certifier that is sound and complete at margin gamma needs at least floor(L/(2 gamma')) queries) — optional. Read T3 §3-4 (${ROOT}/research/theory/T3-contexts-idealization-export.md, repaired).` },
  { key: 'gibbs', file: 'InfLearn/NoAdaptation.lean', task: `Formalize T5 Thm 2.1(i) (no adaptation with private randomness): finite input list x_1..x_N over a finite type X, finite label type Y, a finite class F of deterministic labelers f : X -> Y with a probability distribution Q on F; a 'product hypothesis' h assigns to each input a probability distribution h(.|x) on Y (independent of other inputs). Prove: max over f in support(Q) of sum_i -log h(f(x_i)|x_i) ≥ E_Q [sum_i -log h(f(x_i)|x_i)] ≥ sum_i H(Q_{x_i}), where Q_{x} is the pushforward distribution of f(x) under Q and H is Shannon entropy (natural log is fine), via Gibbs' inequality (prove Gibbs from Real.log_le_sub_one_of_pos or similar available lemmas; only Mathlib modules already built via InfLearn.Prelude are available, which includes Mathlib.Analysis.SpecialFunctions.Log.Basic). Also prove the uniform-on-F(x) hypothesis attains sum_i log|F(x_i)| (where F(x) = {f(x) : f ∈ F}) and that this equals the bound when Q makes each Q_x uniform on F(x). Read T5 §2 in ${ROOT}/research/theory/T5-steeper-simplicity-and-normativity-from-imitation.md.` },
]
phase('Modules')
const mods = await parallel(MODULES.map(m => () => agent(`${MODCOMMON}\n\nYOUR FILE: ${LEAN}/${m.file}\nTASK: ${m.task}`, { label: `lean:${m.key}`, phase: 'Modules', schema: MOD_SCHEMA })))

phase('Integrate')
const integ = await agent(`${ENV}

Wave-2 module agents have written NEW files under ${LEAN}/InfLearn/ (Bilateral, Specker, ParadoxLowerBound, Unstructured, Export, NoAdaptation) on top of the existing, already-integrated modules. Their summaries:
${JSON.stringify(mods.filter(Boolean), null, 1)}

TASK (integrator): (1) add the new modules to ${LEAN}/InfLearn.lean and run 'cd ${LEAN} && lake build'. Fix any errors (including name clashes) minimally, without weakening theorems. (2) Grep for 'sorry', 'axiom', 'native_decide' and report. (3) Extend ${LEAN}/Audit.lean with '#print axioms' lines for the new main theorems; build Audit and capture the output to ${LEAN}/audit-output.txt. (4) UPDATE (do not rewrite from scratch) ${LEAN}/README.md: build instructions (including the note that Mathlib's cache was unavailable so the needed Mathlib subset was compiled from source; 'lake exe cache get' works where the cache is reachable), and a table mapping each paper theorem (T1..T7 numbering, and later paper numbering) to its Lean name, file, and faithfulness (exact / special case / weaker), with honest notes on what is not formalized. Return a structured summary.`, { label: 'lean:integrate', phase: 'Integrate', schema: MOD_SCHEMA })
return { found, mods, integ }
