export const meta = {
  name: 'write-paper-part2a',
  description: 'Draft paper sections (LaTeX) from verified theory files: informal, physics',
  phases: [{ title: 'Draft', detail: 'one writer per section (+ its proof appendix)' }, { title: 'Check', detail: 'independent fidelity check per section' }],
}
const ROOT = '/home/user/AI-works/inferential-learning'
const P = ROOT + '/paper'
const SECTIONS = [
 {
  "key": "informal",
  "title": "Informal mathematics: learning a latent formalization",
  "app": true,
  "pages": 12,
  "sources": "/home/user/AI-works/inferential-learning/research/theory/T4-informal-math-latent-formalization.md (all, as repaired; note the fatal fix to Thm 3.4(d) and the major fixes to Prop 3.6, Thm 5.2(iv), Thm 6.2(c), Prop 6.5), /home/user/AI-works/inferential-learning/research/verification/T4-informal-math-latent-formalization-verification.md, /home/user/AI-works/inferential-learning/research/lit/L6-informal-math-and-formalization-history.md (history: three channels, counterexample objects, Lakatos, Zermelo 1908, Incurvati-Murzi 2017, Manders/System E, de Bruijn factor), /home/user/AI-works/inferential-learning/research/lit/L10-user-notes-digest.md (the user's questions: 'how come mathematicians ended up with such a nice notion of proof?', robust-core hypothesis)",
  "content": "Per OUTLINE \u00a710. Structure: 10.1 the model (latent formalization h*=(L*,R*,rho*,M*), bounded gap g with library, links/equivocation, three channels P/C/O); 10.2 sound bounded-gap verification (Thm 2.4, Prop 2.3 equivocation \u2014 Cauchy's sum theorem, Thm 2.5, Thm 2.7/Prop 2.8 completeness by expansion); 10.3 what practice can identify (Lemma 3.3 informal completeness lemma, Thm 3.4 as repaired, Props 3.5-3.7: ontology and latent language are not identifiable \u2014 standard vs nonstandard reals, epsilon-delta vs IST, von Neumann vs Zermelo numerals); 10.4 counterexample objects versus paradoxes (Lemma 4.1 descent, Thm 4.3 log2|H|, Thm 4.4 chain-paradox/sorites lower bound |H|-1, Thm 4.5/Prop 4.6 bounded bags linear in r, Conjecture); 10.5 Frege -> Russell -> Zermelo (Thm 5.1, Thm 5.2 toy as repaired, Prop 5.4, Incurvati-Murzi); 10.6 the robust core and the emergence of a notion of proof (Thm 6.2 as repaired, Thm 6.3/Prop 6.4, Prop 6.5 as repaired); 10.7 historical reading (L6): how informal math stayed reliable \u2014 object counterexamples dominant, rigor as deliberate monster-hunting; what a learner 'before formalization' would have needed; the hardest open problem (affordable soundness with language invention). Make clear this is the paper's answer to success criterion 2 ('a setup that would have worked before we knew how to formalize proofs'), and be honest that soundness is relative to realizability of the latent formalization class."
 },
 {
  "key": "physics",
  "title": "Contexts, idealization, and checking physics",
  "app": true,
  "pages": 14,
  "sources": "/home/user/AI-works/inferential-learning/research/theory/T3-contexts-idealization-export.md (all, as repaired \u2014 note the repaired Def 5.2 checklist, Thm 3.9(c) hypothesis, Thm 2.4 scope, the repaired sps_checker), /home/user/AI-works/inferential-learning/research/verification/T3-contexts-idealization-export-verification.md, /home/user/AI-works/inferential-learning/research/theory/T2-coherence-as-negative-data.md (Prop 7.1), /home/user/AI-works/inferential-learning/research/theory/T6-philosophical-completeness.md (\u00a74 contexts: belief states vs worlds, contextuality \u2014 cite as forward pointer to Section 9), /home/user/AI-works/inferential-learning/research/lit/L7-contexts-idealization-inconsistency.md (McCarthy ist, chunk-and-permeate, Norton, Wilson, Laymon, McMullin, compositional modeling), /home/user/AI-works/inferential-learning/research/lit/L9-physics-solutions-verification.md (structure of olympiad solutions; four logical roles of physicists' checks; worked problems), /home/user/AI-works/inferential-learning/research/lit/L10-user-notes-digest.md (user's questions: 'true in the context at hand: wtf is that?', 'a dance with many clear setups', air pressure = 0, 100 = 99.9)",
  "content": "Per OUTLINE \u00a711. Structure: 11.1 the problem (eternalism vs contexts; user's air-pressure example; three import regimes \u2014 supposition, counterfactual, idealization; physics idealizations are not counterfactuals); 11.2 filter semantics for contexts (frames, SUP exact discharge Prop 1.5, DEF as push-forward along declared deformation, Prop 1.4 Los, Lemma 1.8 import soundness (one direction only, as repaired), germ semantics for limit-inconsistent idealizations); 11.3 what coherence should constrain (Thm 2.1 eternalism impossible, Cor 2.2, Thm 2.4 realizability criterion with its repaired scope, Thm 2.5/Cor 2.6 soundness and blame localization, T2 Prop 7.1 mis-designation forces global paraconsistency \u2014 formal version of the air-pressure worry, Thm 1.9 reductio hygiene \u2014 the user's warning about proofs by contradiction in inadequate frameworks, Prop 1.10 continuity asymmetry \u2014 '100 = 99.9'); 11.4 export: no free export (Lemma 3.2/Thm 3.3; credit information-based complexity as the standard kernel argument), Prop 3.4 radius of information, certificates (Thm 3.5, Gronwall 3.6, projectile 3.7 with the right numbers, chains 3.8), adversarial stipulation (Thm 3.9 with repaired hypotheses); 11.5 learning tolerances and validity regions (Thm 4.1 coherence cannot calibrate tolerances, Thm 4.3 conformal fails under selection, Thm 4.4, Thm 4.5 Lipschitz certifier, Thm 4.6 monotone certifier (repaired constants), Prop 4.7 Laymon monotonicity can fail); 11.6 the Structured Physics Solution checker (format; Def 5.2 checklist as repaired; Thm 5.3 relative soundness; Thm 5.4 the judgment layer is ineliminable; Thm 5.5 supervaluational correctness = the answer to 'true in the context at hand'; Prop 5.6 Gricean one-sidedness; the table of one-sided signals); 11.7 worked example EuPhO 2025 T1(a) (Props 6.1-6.3; mini-checker accept/reject table, with the honest note on the prototype's residual defects after repair); 11.8 the four logical roles of physicists' checks (L9). Be explicit that this is a checker, not a solver, and that soundness is relative to the reading and the top model (J1-J3)."
 }
]

const SUM = { type: 'object', properties: {
  files: { type: 'array', items: { type: 'string' } },
  compiles: { type: 'boolean' },
  approx_pages_main: { type: 'number' }, approx_pages_appendix: { type: 'number' },
  results: { type: 'array', items: { type: 'object', properties: { label: { type: 'string' }, kind: { type: 'string' }, source: { type: 'string' }, one_line: { type: 'string' }, status: { type: 'string' } }, required: ['label', 'kind', 'source', 'one_line', 'status'] } },
  concerns: { type: 'array', items: { type: 'string' } } }, required: ['files', 'compiles', 'approx_pages_main', 'approx_pages_appendix', 'results', 'concerns'] }
const CHK = { type: 'object', properties: { issues: { type: 'array', items: { type: 'object', properties: { location: { type: 'string' }, severity: { type: 'string', enum: ['fatal', 'major', 'minor'] }, problem: { type: 'string' }, fix_applied: { type: 'boolean' } }, required: ['location', 'severity', 'problem', 'fix_applied'] } }, compiles_after: { type: 'boolean' }, summary: { type: 'string' } }, required: ['issues', 'compiles_after', 'summary'] }

const writerPrompt = s => `You are writing one section of a research paper (LaTeX) for a mathematically and philosophically literate audience. Project context: ${ROOT}/research/00-brief.md (the question), ${ROOT}/research/02-master-plan.md (thesis), ${P}/OUTLINE.md (section plan and theorem sources — follow it), ${P}/NOTATION.md (MANDATORY unified notation), ${P}/preamble.tex (macros and theorem environments; do not edit it — if you need a new macro, define it with \\providecommand at the top of your own file).

YOUR SECTION: ${s.title} — main file ${P}/sections/${s.key}.tex${s.app ? `, proof appendix ${P}/sections/app-${s.key}.tex` : ''}, references ${P}/bib/${s.key}.bib (BibTeX; real references only, taken from the project's literature memos; omit anything you cannot attribute confidently).
SOURCES: ${s.sources}. IMPORTANT: the theory files have been adversarially verified; each ends with a '## Verification log' and there are reports in ${ROOT}/research/verification/. Use the REPAIRED statements and scopes; never reintroduce a retracted or overstated claim.
CONTENT: ${s.content}

Requirements:
- Start with \\section{...}\\label{sec:${s.key}}${s.app ? ` and the appendix file with \\section{Proofs for Section~\\ref{sec:${s.key}}}\\label{app:${s.key}}` : ''}. Label theorems as thm:${s.key}:<short>, lem:..., prop:..., def:..., etc. Cross-section references use labels sec:setting, sec:search, sec:caution, sec:imitation, sec:coherence, sec:twotier, sec:simplicity, sec:existence, sec:informal, sec:physics, sec:experiments, sec:philosophy, sec:open (and app:<key>).
- Main text: motivate each result in a sentence or two, define precisely, state theorems precisely (with all hypotheses), give short proofs inline when they are a few lines, otherwise a proof idea plus 'Full proof in Appendix~\\ref{app:${s.key}}'. After major results add a short 'Reading' paragraph explaining what it means for the user's question (learning which inferences are valid; coherence; contexts; justification). Credit known results explicitly (e.g. 'This is essentially Natarajan (1987)'); say when a result is 'trivial once set up'.
- Mark each theorem's provenance with \\src{...} pointing to the research file and its numbering (e.g. \\src{T1 Thm 3.1}); mark status with \\status{proof sketch}/\\status{computed}/\\status{conjecture} where applicable.
- Appendix: complete rigorous proofs (adapt from the sources; fix presentation; do not invent new claims). If a source proof is only a sketch, keep it labelled as a sketch.
- Length: main text roughly ${s.pages} pages; appendix as long as needed.
- Must compile: run ${P}/test-section.sh ${s.key}${s.app ? ` app-${s.key}` : ''} and fix all LaTeX errors (undefined cross-section references are fine).
Return the structured summary (list every theorem/lemma/definition you stated with its label and source).`

const checkPrompt = (s, w) => `You are a meticulous referee checking a drafted paper section against its sources. Section files: ${P}/sections/${s.key}.tex${s.app ? ` and ${P}/sections/app-${s.key}.tex` : ''}. Sources: ${s.sources} (use the repaired statements: see each theory file's '## Verification log' and ${ROOT}/research/verification/). Check: (1) every theorem statement in the draft matches a verified source statement (hypotheses not dropped, scope not widened, constants right); (2) proofs in the appendix are complete and correct (no silent gaps); (3) no retracted/overstated claims (e.g. claims fixed in verification logs); (4) notation follows ${P}/NOTATION.md; (5) citations are real and correctly attributed; (6) the prose does not overclaim novelty or generality. FIX problems directly in the section files (minimal edits), re-run ${P}/test-section.sh ${s.key}${s.app ? ` app-${s.key}` : ''} to ensure it compiles, and report each issue with fix_applied. Writer's summary for reference: ${JSON.stringify(w || {}).slice(0, 6000)}`

phase('Draft')
const out = await pipeline(SECTIONS,
  s => agent(writerPrompt(s), { label: `write:${s.key}`, phase: 'Draft', schema: SUM }),
  (w, s) => agent(checkPrompt(s, w), { label: `check:${s.key}`, phase: 'Check', schema: CHK }).then(c => ({ key: s.key, writer: w, check: c })))
return out
