export const meta = {
  name: 'write-paper-part2b',
  description: 'Draft paper sections (LaTeX) from verified theory files: simplicity, existence',
  phases: [{ title: 'Draft', detail: 'one writer per section (+ its proof appendix)' }, { title: 'Check', detail: 'independent fidelity check per section' }],
}
const ROOT = '/home/user/AI-works/inferential-learning'
const P = ROOT + '/paper'
const SECTIONS = [
 {
  "key": "simplicity",
  "title": "Simplicity and normativity from imitation",
  "app": true,
  "pages": 9,
  "sources": "/home/user/AI-works/inferential-learning/research/theory/T5-steeper-simplicity-and-normativity-from-imitation.md (all, as repaired; note the fatal fix to Thm 3.3 clause 2 and the many minor fixes, e.g. Prop 2.3 threshold, Thm 2.5(c) kappa, Cor 3.4, Prop 4.4 hypotheses, (d3) and (d6), Cor 5.2a hypotheses, Prop 5.4 quantification), /home/user/AI-works/inferential-learning/research/verification/T5-verification.md, /home/user/AI-works/inferential-learning/research/theory/T4-informal-math-latent-formalization.md (\u00a77 Props 7.1-7.3, as repaired), /home/user/AI-works/inferential-learning/research/lit/L10-user-notes-digest.md and the user's note /home/user/kaarelh/notes/philosophy/philosophy of thinking/beating solomonoff induction at grokking a notion.md (quote the user's proposal briefly and precisely; this section answers it), /home/user/AI-works/inferential-learning/research/lit/L11-justification-and-reflective-equilibrium.md (Stich/Cohen competence vs performance)",
  "content": "Per OUTLINE \u00a78. This section answers a question posed by the person who asked for this work (cite as 'a proposal in K. H\u00e4nni's notes' \u2014 keep it respectful and precise): can a steeper simplicity penalty on function induction with private per-input randomness extract the intended rules rather than the teacher's systematic errors? Structure: 8.1 the proposal and its formalization (two-part objective c*l(h)+R(h); idealized K version and computable class version; lambda = cN; relation to tempered posteriors / generalized Bayes learning rate eta = 1/lambda (Gr\u00fcnwald) and to Kolmogorov's structure function and algorithmic sufficient statistics (Vereshchagin & Vit\u00e1nyi 2004) \u2014 cite carefully, mark unverified if the memo does); 8.2 no universal hypothesis in the function case (Thm 2.1; Prop 2.3 sequence pathology with the corrected threshold; Prop 2.6 in-context universality returns at block granularity \u2014 an argument for step-level checkers); 8.3 the kink (Thm 2.5 shared vs private randomness \u2014 the precise vindication of the proposal's convex-hull/kink intuition; include the p-range caveat); 8.4 selection traces the hull: rate thresholds (Lemma 3.1, Thm 3.2, Thm 3.3 as repaired, Cor 3.4); 8.5 pathologies (Thm 4.1 rate blindness, rate-inversion counterexample T4 Prop 7.3 (Lean-formalized: InfLearn.RateThreshold.valid_not_minimizer), Thm 4.3 c is not identifiable from imitation data \u2014 held-out human data prefers the error model, Prop 4.4 guard erosion with its hypotheses, other pathologies briefly); 8.6 the division of labour (Thm 5.2: simplicity removes high-description-cost errors; coherence removes incoherent ones; world feedback removes empirically refutable ones; meaning postulates (Prop 5.4) as a rate-independent second channel; Prop 5.3 repair by sacrifice; residue); 8.7 verdict in the user's terms: where the hope is vindicated, where it fails. Use \\leanok{RateThreshold.rate_threshold} etc. where applicable (see /home/user/AI-works/inferential-learning/lean/README.md)."
 },
 {
  "key": "existence",
  "title": "Coherence and existence: a 'philosophical completeness theorem'",
  "app": true,
  "pages": 9,
  "sources": "/home/user/AI-works/inferential-learning/research/theory/T6-philosophical-completeness.md (all, as repaired), /home/user/AI-works/inferential-learning/research/verification/T6-verification.md, the user's note /home/user/kaarelh/notes/logic/a 'philosophical version' of g\u00f6del's completeness theorem.md (quote the question), /home/user/AI-works/inferential-learning/research/lit/L4-inferentialism-and-categoricity.md, /home/user/AI-works/inferential-learning/research/lit/L5-logic-facts.md, /home/user/AI-works/inferential-learning/lean/README.md (for Lean cross-references, e.g. Carnap module Lemma 4.1 = Val(mrel V) = closure V)",
  "content": "Per OUTLINE \u00a79. Answers the question 'a mode of talking makes sense (is coherent) iff there is something it could be talking about \u2014 is a generalization of the completeness theorem available?'. Structure: 9.1 the Galois connection Mod \u22a3 Th; strong vs weak completeness; Prop 1.3 (Sam's image question = strong completeness), Thm 1.4 (tautological completeness: every calculus is complete for its own closed sets, so content requires an independently specified semantics), Thm 1.5 (completeness = realization of points), Prop 1.6 (weak \u2260 strong, IPC); 9.2 positions (Thm 2.2/Cor 2.3 bilateral Lindenbaum; Thm 2.4 Stone duality; Thm 2.6 structural calculi and Lindenbaum bundles); 9.3 credences (Thm 3.1 de Finetti via counting sequents; Thm 3.4 and Thm 3.5: no bounded-arity, CCS-style constraint family characterizes coherence \u2014 connect explicitly to consistency-based probing of language models (Burns et al. 2022 CCS) as a caution; Prop 3.6 closed agendas; Thm 3.7 Gaifman coherence; Thm 3.8 probabilistic omega-rule pins Th(N); Cor 3.9 logical inductors' limits are non-standard); 9.4 contexts (Thm 4.1/Cor 4.2 multi-context completeness for belief-state semantics; Thm 4.5 rules of proof vs conditionals \u2014 belief states not worlds; Thm 4.6/Prop 4.7 local-to-global and contextuality \u2014 frames needn't be jointly realizable); 9.5 what coherence of a learned calculus buys (Thm 5.1, Thm 5.2 Leibniz collapse, Prop 5.3), categoricity and pinning (Thm 5.5 prime models, compactness barrier Thm 5.6, computability barrier Thm 5.7, anchoring = Beth Prop 5.8, Tennenbaum); 9.6 verdict: the proposition is true in a precise generalized sense (existence of a model) and false in the intended sense (standard/intended existence needs categoricity, anchoring, or an infinitary condition, and cannot be computably certified beyond Pi1)."
 }
]

const SUM = { type: 'object', properties: {
  files: { type: 'array', items: { type: 'string' } },
  compiles: { type: 'boolean' },
  approx_pages_main: { type: 'number' }, approx_pages_appendix: { type: 'number' },
  results: { type: 'array', items: { type: 'object', properties: { label: { type: 'string' }, kind: { type: 'string' }, source: { type: 'string' }, one_line: { type: 'string' }, status: { type: 'string' } }, required: ['label', 'kind', 'source', 'one_line', 'status'] } },
  concerns: { type: 'array', items: { type: 'string' } } }, required: ['files', 'compiles', 'approx_pages_main', 'approx_pages_appendix', 'results', 'concerns'] }
const CHK = { type: 'object', properties: { issues: { type: 'array', items: { type: 'object', properties: { location: { type: 'string' }, severity: { type: 'string', enum: ['fatal', 'major', 'minor'] }, problem: { type: 'string' }, fix_applied: { type: 'boolean' } }, required: ['location', 'severity', 'problem', 'fix_applied'] } }, compiles_after: { type: 'boolean' }, summary: { type: 'string' } }, required: ['issues', 'compiles_after', 'summary'] }

const writerPrompt = s => `You are writing one section of a research paper (LaTeX) for a mathematically and philosophically literate audience. Project context: ${ROOT}/research/00-brief.md (the question), ${ROOT}/research/02-master-plan.md (thesis), ${P}/OUTLINE.md (section plan and theorem sources — follow it), ${P}/NOTATION.md (MANDATORY unified notation), ${P}/preamble.tex (macros and theorem environments; do not edit it — if you need a new macro, define it with \\providecommand at the top of your own file).

YOUR SECTION: ${s.title} — main file ${P}/sections/${s.key}.tex${s.app ? `, proof appendix ${P}/sections/app-${s.key}.tex` : ''}, references ${P}/bib/${s.key}.bib (BibTeX; real references only, taken from the project's literature memos; omit anything you cannot attribute confidently).
SOURCES: ${s.sources}. IMPORTANT: the theory files have been adversarially verified; each ends with a '## Verification log' and there are reports in ${ROOT}/research/verification/. Use the REPAIRED statements and scopes; never reintroduce a retracted or overstated claim.
CONTENT: ${s.content}

Requirements:
- Start with \\section{...}\\label{sec:${s.key}}${s.app ? ` and the appendix file with \\section{Proofs for Section~\\ref{sec:${s.key}}}\\label{app:${s.key}}` : ''}. Label theorems as thm:${s.key}:<short>, lem:..., prop:..., def:..., etc. Cross-section references use labels sec:setting, sec:search, sec:caution, sec:imitation, sec:coherence, sec:twotier, sec:simplicity, sec:existence, sec:informal, sec:physics, sec:experiments, sec:philosophy, sec:open (and app:<key>).
- Main text: motivate each result in a sentence or two, define precisely, state theorems precisely (with all hypotheses), give short proofs inline when they are a few lines, otherwise a proof idea plus 'Full proof in Appendix~\\ref{app:${s.key}}'. After major results add a short 'Reading' paragraph explaining what it means for the user's question (learning which inferences are valid; coherence; contexts; justification). Credit known results explicitly (e.g. 'This is essentially Natarajan (1987)'); say when a result is 'trivial once set up'.
- Mark each theorem's provenance with \\src{...} pointing to the research file and its numbering (e.g. \\src{T1 Thm 3.1}); mark status with \\status{proof sketch}/\\status{computed}/\\status{conjecture} where applicable.
- Appendix: complete rigorous proofs (adapt from the sources; fix presentation; do not invent new claims). If a source proof is only a sketch, keep it labelled as a sketch.
- Length: main text roughly ${s.pages} pages; appendix as long as needed.
- Must compile: run ${P}/test-section.sh ${s.key}${s.app ? ` app-${s.key}` : ''} and fix all LaTeX errors (undefined cross-section references are fine).
Return the structured summary (list every theorem/lemma/definition you stated with its label and source).`

const checkPrompt = (s, w) => `You are a meticulous referee checking a drafted paper section against its sources. Section files: ${P}/sections/${s.key}.tex${s.app ? ` and ${P}/sections/app-${s.key}.tex` : ''}. Sources: ${s.sources} (use the repaired statements: see each theory file's '## Verification log' and ${ROOT}/research/verification/). Check: (1) every theorem statement in the draft matches a verified source statement (hypotheses not dropped, scope not widened, constants right); (2) proofs in the appendix are complete and correct (no silent gaps); (3) no retracted/overstated claims (e.g. claims fixed in verification logs); (4) notation follows ${P}/NOTATION.md; (5) citations are real and correctly attributed; (6) the prose does not overclaim novelty or generality. FIX problems directly in the section files (minimal edits), re-run ${P}/test-section.sh ${s.key}${s.app ? ` app-${s.key}` : ''} to ensure it compiles, and report each issue with fix_applied. Writer's summary for reference: ${JSON.stringify(w || {}).slice(0, 6000)}`

phase('Draft')
const out = await pipeline(SECTIONS,
  s => agent(writerPrompt(s), { label: `write:${s.key}`, phase: 'Draft', schema: SUM }),
  (w, s) => agent(checkPrompt(s, w), { label: `check:${s.key}`, phase: 'Check', schema: CHK }).then(c => ({ key: s.key, writer: w, check: c })))
return out
