import InfLearn.Steps

/-!
# Contexts: no truth-functional eternal reading, reductio hygiene, mis-designation

This file formalizes three results about contexts.

## Part 1 — T3 §1.2–§2.1 in a propositional toy

The *parameter points* of T3 Def 1.1 are Boolean valuations `ℕ → Bool`, and the sentences are
the shared propositional `Formula`s.  A context is represented by its filter `F` on parameter
points, as in T3 Def 1.3, and

* `c ⊨ φ` is `HoldsIn F φ := ‖φ‖ ∈ F`, where `‖φ‖ = truthSet φ`;
* `c` is proper iff `∅ ∉ F` (`Proper F`).

The two special cases the task names are both instances.
* *Truth at one designated idealized world `w_c`*: `F = pure w_c` (`holdsIn_pure`).
* *Truth in all worlds of a model class `K`*: `F = 𝓟 K` (`holdsIn_principal`).

The general filter form also covers germ semantics.

Supporting results (toy versions of T3 §1.2–1.3):
* `cn2_closed_ThIn` and `consistent_ThIn_iff`: **T3 Prop 1.4(a),(b).**  `Th(c)` is closed under
  classical consequence (by compactness), and it is consistent iff `c` is proper.
* `holdsIn_sup_iff`: **T3 Prop 1.5.**  SUP is exact discharge: `F ⊓ 𝓟‖A‖ ⊨ ψ ↔ F ⊨ A → ψ`.
* `defFilter`: the DEF filter of Def 1.3, generated by the sets `δ(F × G)`.  Here
  `δ(λ, μ) = λ[D := μ]` deforms the atoms in a finite set `D`.
  `defFilter_pure_pure` shows that under limit semantics below the root, `defFilter` is the
  principal filter at the single idealized world `λ*[D := λ°]`.
* `import_sound`: **T3 Lemma 1.8(a).**  `D`-stable sentences, for example those with no atom in
  `D` (`dStable_of_disjoint`), are soundly imported into every DEF child.

**T3 Theorem 2.1** (no truth-functional eternal reading):
* `no_truthFunctional_eternal_reading`: for a proper context `F`, a stipulation `S` with
  `F ⊨ S` and `S` false at the actual point `w₀`, and *any* `f : Bool → Bool → Bool`, the
  reading `φ ↦ f (S^{w₀}) (φ^{w₀})` does not track in-context truth.
* `eternal_reading_witnesses`: the paper's generic witnesses `φ := ⊤` and `ψ := ¬S`.  They
  have the same actual truth value but different in-context truth.
* `stripping_fails` and `conditionalizing_fails`: the two named readings.
* `tracksAt_conditional_of_not_proper`: the properness hypothesis is needed.  For an improper
  context, conditionalizing tracks in-context truth exactly, as in the paper's rope remark.
* `no_eternal_reading_pure`, `no_eternal_reading_modelClass` and `patm_example`: the
  single-idealized-world, model-class and concrete DEF ("`p_atm = 0`") instances.

## Part 2 — T3 Theorem 1.9 (reductio hygiene)

A reductio of `A` from the imported fragment `K` with the rule instances `R` is
`Refutes R K A := ⊥ ∈ Cl R (K ∪ {A})`, using the step-derivation calculus of `InfLearn.Steps`.

* `refutes_of_inconsistent`: **(b)**.  If `K ⊢_R ⊥`, every sentence is refuted.
* `hygiene_K_unsat`, `hygiene_K1_sat`, `hygiene_K2_sat`, `hygiene_K1_supp_unsat` and
  `hygiene_K2_supp_unsat`: **(c)**, the truth-table facts about `K = {A → q, ¬A → q, ¬q}`.
* `DA_valid` and `DA_soundRules`: the explicit derivations `D_A` and `D_{¬A}`.  Each uses a
  modus ponens instance and a `¬`-elimination instance, both classically sound.
* `derivation_local_test_accepts_both`: **(c)**, indistinguishability.  Every test that is a
  function of the derivation alone and accepts every sound reductio from a consistent premise
  set accepts both `D_A` and `D_{¬A}`.  Both use only premises from `K`, and their conclusions
  `¬A` and `¬¬A` are jointly unsatisfiable.  `derivation_local_test_accepts_both'` is the same
  with "sound" read semantically (premises plus supposition unsatisfiable).
* `certificate_refutes_false` and `certificate_not_both`: **(d)**.  A valuation satisfying `K`
  and every rule instance used falsifies every refuted `A`.
  `certificate_rules_needed` gives the paper's counterexample: `K = {¬q}` is satisfiable, yet
  with the context-relatively sound instance `/q` every `A` and every `¬A` is refuted.
* `refutation_sound_in_context` and `proper_not_both_refuted`: **(a)** in the filter
  semantics, together with the existence half of (d).  If `c ⊨ K` and every rule instance is
  `c`-sound, then a reductio of `A` yields `c ⊨ ¬A`.  A proper context therefore never refutes
  both `A` and `¬A`.

## Part 3 — T2 Proposition 7.1 (mis-designation forces global sub-classicality)

* `closure_eq_univ_of_contradictory`: if `Cn2 ≤ C`, every context containing `α` and `¬α`
  has `C`-closure `univ`.
* `not_Cn2_le_of_consistent_unsat` and `not_Cn2_le_of_coherent_unsat`: a `C` that is
  consistent (or coherent, i.e. non-trivial) on a classically inconsistent context cannot
  extend `Cn2`.
* `not_Cn2_le_of_coherent_contradictory`: the task's form.  A structural `C` that is coherent on
  a designated context containing `α` and `¬α` cannot extend `Cn2`.
* `misdesignation_not_Cn2_le`: **7.1(a), first claim**, for an `𝒜`-coherent `C`
  (`DesignatedCoherent C 𝒜`: `⊥ ∉ C A` for every `A ∈ 𝒜`).
* `exists_invalid_step` and `exists_invalid_schema`: **7.1(a), second claim.**  For every
  derivation of `⊥` from a designated context, some step it uses is not `C`-valid.  If the
  steps are instances of schemata `D`, then, given structurality, some schema of `D` (its most
  general instance) is not `C`-valid.
* `atomic_paraconsistent` and `atomic_nontrivial`: **7.1(b).**  If a structural `C` is
  consistent (respectively coherent) on a context containing `α` and `¬α`, then
  `p, ¬p ⊬_C ⊥` (respectively `C {p, ¬p} ≠ univ`) for every atom `p`.

Structurality is *not* needed for 7.1(a)'s first claim; it is needed for the schema claim and
for (b).

## Faithfulness notes

* **T3 Thm 2.1.**  The paper works with first-order deformation frames over real parameters.
  The toy replaces parameter points by valuations and sentences by propositional formulas.
  The paper's proof uses only three facts: in-context truth is membership of truth sets in a
  filter; `c ⊨ ⊤`; and a proper filter never contains both `‖S‖` and `‖¬S‖`.  All three hold
  in the toy, so the argument is reproduced in full.  The statement is proved for an
  *arbitrary* proper filter, which covers limit and germ semantics, model classes and a single
  idealized world, and for *every* `f`.
* **T3 Thm 1.9(c).**  The satisfiability facts need `A` and `q` to be distinct atoms.  The
  unsatisfiability facts and the derivations hold for arbitrary formulas `A` and `q`.  "A test
  that is a function of the derivation alone" is a predicate on `Reductio` (rule instances
  used, premises used, supposition).  It sees neither the full imported fragment nor the
  context.
* **T2 Prop 7.1.**  "Coherent" is read as `⊥ ∉ C A` (T2's reading when `⊥` is present), and
  also as non-triviality `C A ≠ Fm` (`ConsOp.Coherent`).  In 7.1(a)'s second claim, "a
  CPC-derivation in step format" is modelled as an arbitrary step derivation `⊥ ∈ Cl R A`, so
  the statement is slightly more general than the paper's.

Everything lives in the namespace `InfLearn.Contexts`.
-/

namespace InfLearn

namespace Contexts

open Formula

/-! ## Part 1. Filter semantics for contexts (propositional toy of T3 Def 1.3) -/

section FilterSemantics

/-- The truth set `‖φ‖ = {u | u ⊨ φ}` of a formula among parameter points (valuations). -/
def truthSet (φ : Formula) : Set Valuation := {u | φ.eval u = true}

@[simp] theorem mem_truthSet {φ : Formula} {u : Valuation} :
    u ∈ truthSet φ ↔ φ.eval u = true := Iff.rfl

/-- In-context truth (T3 Def 1.3).  A context is given by its filter `F` on parameter points,
and `c ⊨ φ` iff `‖φ‖ ∈ F`. -/
def HoldsIn (F : Filter Valuation) (φ : Formula) : Prop := truthSet φ ∈ F

/-- The theory `Th(c) = {φ | c ⊨ φ}` of a context. -/
def ThIn (F : Filter Valuation) : Set Formula := {φ | HoldsIn F φ}

/-- A context is *proper* if its filter does not contain `∅` (T3 Def 1.3). -/
def Proper (F : Filter Valuation) : Prop := ∅ ∉ F

theorem proper_iff_ne_bot {F : Filter Valuation} : Proper F ↔ F ≠ ⊥ := by
  rw [Proper, Filter.empty_mem_iff_bot]

theorem truthSet_top : truthSet Formula.top = Set.univ := by
  ext u; simp

theorem truthSet_bot : truthSet Formula.bot = ∅ := by
  ext u; simp

theorem truthSet_neg (φ : Formula) : truthSet (neg φ) = (truthSet φ)ᶜ := by
  ext u; simp

theorem holdsIn_top (F : Filter Valuation) : HoldsIn F Formula.top := by
  rw [HoldsIn, truthSet_top]; exact Filter.univ_mem

theorem holdsIn_bot_iff {F : Filter Valuation} : HoldsIn F Formula.bot ↔ ¬ Proper F := by
  rw [HoldsIn, truthSet_bot, Proper, not_not]

theorem HoldsIn.mono {F : Filter Valuation} {φ ψ : Formula} (h : HoldsIn F φ)
    (hφψ : ∀ u, φ.eval u = true → ψ.eval u = true) : HoldsIn F ψ :=
  Filter.mem_of_superset h fun u hu => hφψ u hu

/-- A proper context never makes both `φ` and `¬φ` true. -/
theorem not_holdsIn_neg_of_holdsIn {F : Filter Valuation} (hF : Proper F) {φ : Formula}
    (h : HoldsIn F φ) : ¬ HoldsIn F (neg φ) := by
  intro hn
  apply hF
  have := Filter.inter_mem h hn
  rwa [truthSet_neg, Set.inter_compl_self] at this

/-- Every model-class context `𝓟 K`: `c ⊨ φ` iff `φ` holds throughout `K`. -/
theorem holdsIn_principal {K : Set Valuation} {φ : Formula} :
    HoldsIn (Filter.principal K) φ ↔ ∀ u ∈ K, φ.eval u = true :=
  Filter.mem_principal

theorem proper_principal_iff {K : Set Valuation} : Proper (Filter.principal K) ↔ K.Nonempty := by
  rw [Proper, Filter.mem_principal, Set.subset_empty_iff, Set.nonempty_iff_ne_empty]

/-- A single designated idealized world `w_c`: `c ⊨ φ` iff `φ` is true at `w_c`. -/
theorem holdsIn_pure {w : Valuation} {φ : Formula} :
    HoldsIn (pure w) φ ↔ φ.eval w = true :=
  Filter.mem_pure

theorem proper_pure (w : Valuation) : Proper (pure w) := by
  intro h; exact (Filter.mem_pure.1 h)

/-- **T3 Prop 1.4(a) (toy).**  `Th(c)` is closed under classical consequence `C₂`.  Infinite
premise sets are handled by compactness. -/
theorem cn2_closed_ThIn (F : Filter Valuation) : Cn2.IsClosed (ThIn F) := by
  intro φ hφ
  obtain ⟨X₀, hX₀, hcons⟩ := SemCons.exists_finset hφ
  have hmem : (⋂ ψ ∈ X₀, truthSet ψ) ∈ F :=
    (Filter.biInter_finset_mem X₀).2 fun ψ hψ => hX₀ hψ
  refine Filter.mem_of_superset hmem ?_
  intro u hu
  simp only [Set.mem_iInter] at hu
  exact hcons u fun ψ hψ => hu ψ hψ

theorem Cn2_ThIn (F : Filter Valuation) : Cn2 (ThIn F) = ThIn F :=
  Cn2.isClosed_iff_eq.1 (cn2_closed_ThIn F)

/-- **T3 Prop 1.4(b) (toy).**  `Th(c)` is consistent (`⊥ ∉ C₂ Th(c)`) iff `c` is proper. -/
theorem consistent_ThIn_iff {F : Filter Valuation} : Consistent Cn2 (ThIn F) ↔ Proper F := by
  unfold Consistent
  rw [Cn2_ThIn]
  change ¬ HoldsIn F Formula.bot ↔ _
  rw [holdsIn_bot_iff, not_not]

theorem satisfiable_ThIn_iff {F : Filter Valuation} : Satisfiable (ThIn F) ↔ Proper F := by
  rw [← Cn2_consistent_iff, consistent_ThIn_iff]

/-- **T3 Prop 1.5 (toy): SUP is exact discharge.**  The supposition context `SUP(A)` under a
parent with filter `F` has the filter generated by `F ∪ {‖A‖}`, which is `F ⊓ 𝓟 ‖A‖`.  Then
`SUP(A) ⊨ ψ ↔ parent ⊨ A → ψ`. -/
theorem holdsIn_sup_iff {F : Filter Valuation} {A ψ : Formula} :
    HoldsIn (F ⊓ Filter.principal (truthSet A)) ψ ↔ HoldsIn F (imp A ψ) := by
  unfold HoldsIn
  rw [Filter.mem_inf_principal]
  have : {x | x ∈ truthSet A → x ∈ truthSet ψ} = truthSet (imp A ψ) := by
    ext u
    simp only [Set.mem_setOf_eq, mem_truthSet]
    exact eval_imp_eq_true.symm
  rw [this]

/-- In particular `SUP(A)` is improper iff the parent proves `¬A` (T3 Prop 1.5). -/
theorem sup_not_proper_iff {F : Filter Valuation} {A : Formula} :
    ¬ Proper (F ⊓ Filter.principal (truthSet A)) ↔ HoldsIn F (neg A) := by
  rw [← holdsIn_bot_iff, holdsIn_sup_iff]
  constructor
  · intro h; exact h.mono fun u hu => by simpa using hu
  · intro h; exact h.mono fun u hu => by simpa using hu

/-! ### Declared deformations (T3 Def 1.2/1.3, propositional toy) -/

/-- `δ(λ, μ) = λ[D := μ]`: replace the coordinates (atoms) in `D` by those of `μ`. -/
def deform (D : Finset ℕ) (lam mu : Valuation) : Valuation :=
  fun n => if n ∈ D then mu n else lam n

theorem deform_of_not_mem {D : Finset ℕ} {lam mu : Valuation} {n : ℕ} (h : n ∉ D) :
    deform D lam mu n = lam n := by
  simp [deform, h]

theorem deform_of_mem {D : Finset ℕ} {lam mu : Valuation} {n : ℕ} (h : n ∈ D) :
    deform D lam mu n = mu n := by
  simp [deform, h]

/-- The DEF filter of T3 Def 1.3.  Given the parent filter `F` and the path `G`, it is
generated by the sets `δ(F' × G')` with `F' ∈ F` and `G' ∈ G`, i.e. it is the image of
`F ×ˢ G` under `δ`.  Here every parameter point is in `dom`, and the path `G` is a filter on
valuations whose coordinates outside `D` are ignored. -/
def defFilter (D : Finset ℕ) (F G : Filter Valuation) : Filter Valuation :=
  Filter.map (fun p : Valuation × Valuation => deform D p.1 p.2) (F ×ˢ G)

/-- Limit semantics below the root: with the principal filters at the actual point `w₀` and at
the ideal value `λ°`, the DEF child is the principal filter at the idealized world
`w₀[D := λ°]`. -/
theorem defFilter_pure_pure (D : Finset ℕ) (w0 lam : Valuation) :
    defFilter D (pure w0) (pure lam) = pure (deform D w0 lam) := by
  rw [defFilter, Filter.prod_pure_pure, Filter.map_pure]

/-- `φ` is `D`-stable (T3 Def 1.7): its truth value does not change when only coordinates in
`D` change. -/
def DStable (D : Finset ℕ) (φ : Formula) : Prop :=
  ∀ lam lam' : Valuation, (∀ n, n ∉ D → lam n = lam' n) → φ.eval lam = φ.eval lam'

/-- Syntactic sufficient condition: no atom of `φ` is deformed ("undeformed data"). -/
theorem dStable_of_disjoint {D : Finset ℕ} {φ : Formula} (h : ∀ n ∈ φ.atoms, n ∉ D) :
    DStable D φ :=
  fun _ _ hl => eval_congr fun n hn => hl n (h n hn)

/-- **T3 Lemma 1.8(a) (toy): import soundness.**  If `φ` is `D`-stable and the parent proves
`φ`, then every DEF child deforming `D` proves `φ`, for any parent filter and any path. -/
theorem import_sound {D : Finset ℕ} {φ : Formula} (hφ : DStable D φ) {F G : Filter Valuation}
    (hp : HoldsIn F φ) : HoldsIn (defFilter D F G) φ := by
  unfold HoldsIn defFilter
  rw [Filter.mem_map]
  refine Filter.mem_of_superset (Filter.prod_mem_prod hp (Filter.univ_mem (f := G))) ?_
  rintro ⟨lam, mu⟩ ⟨hlam, -⟩
  simp only [Set.mem_preimage, mem_truthSet] at hlam ⊢
  rw [hφ (deform D lam mu) lam fun n hn => deform_of_not_mem hn]
  exact hlam

end FilterSemantics

/-! ## T3 Theorem 2.1: no truth-functional eternal reading -/

section Eternal

/-- A candidate *eternal reading* of "φ holds in `c`" is a world sentence `τ(c, φ)` whose
truth value at the actual point `w₀` is `f (S^{w₀}) (φ^{w₀})`.  `TracksAt F S w₀ f` says that
this reading agrees with in-context truth for **every** formula `φ`. -/
def TracksAt (F : Filter Valuation) (S : Formula) (w0 : Valuation)
    (f : Bool → Bool → Bool) : Prop :=
  ∀ φ : Formula, f (S.eval w0) (φ.eval w0) = true ↔ HoldsIn F φ

/-- **T3 Thm 2.1, witnesses.**  For a proper context `c` that stipulates `S`, with `S` false at
`w₀`, take `φ := ⊤` and `ψ := ¬S`.  They have the same actual truth value (both true), yet
`c ⊨ φ`, `c ⊨ ¬ψ` (i.e. `c ⊨ S`) and `c ⊭ ψ`. -/
theorem eternal_reading_witnesses {F : Filter Valuation} (hF : Proper F) {S : Formula}
    {w0 : Valuation} (hS : HoldsIn F S) (hS0 : S.eval w0 = false) :
    Formula.top.eval w0 = (neg S).eval w0 ∧ HoldsIn F Formula.top ∧ HoldsIn F S ∧
      ¬ HoldsIn F (neg S) := by
  refine ⟨by simp [hS0], holdsIn_top F, hS, not_holdsIn_neg_of_holdsIn hF hS⟩

/-- **T3 Theorem 2.1 (no truth-functional eternal reading of idealized claims).**  Let `c` be
a context that is proper at `w₀`, with a stipulation `S` that holds in `c` but is false at the
actual point `w₀`.  Then no reading of "φ holds in `c`" whose truth value at `w₀` is a
function `f` of the actual truth values of `S` and `φ` tracks in-context truth. -/
theorem no_truthFunctional_eternal_reading {F : Filter Valuation} (hF : Proper F) {S : Formula}
    {w0 : Valuation} (hS : HoldsIn F S) (hS0 : S.eval w0 = false) (f : Bool → Bool → Bool) :
    ¬ TracksAt F S w0 f := by
  intro htr
  obtain ⟨heq, htop, -, hnot⟩ := eternal_reading_witnesses hF hS hS0
  apply hnot
  have h1 := (htr Formula.top).2 htop
  rw [heq] at h1
  exact (htr (neg S)).1 h1

/-- The same statement, quantified: there is no `f : Bool → Bool → Bool` with
`[c ⊨ φ] = f (S^{w₀}) (φ^{w₀})` for all `φ`. -/
theorem not_exists_truthFunctional_reading {F : Filter Valuation} (hF : Proper F)
    {S : Formula} {w0 : Valuation} (hS : HoldsIn F S) (hS0 : S.eval w0 = false) :
    ¬ ∃ f : Bool → Bool → Bool, ∀ φ : Formula, (HoldsIn F φ ↔ f (S.eval w0) (φ.eval w0) = true) :=
  fun ⟨f, hf⟩ => no_truthFunctional_eternal_reading hF hS hS0 f fun φ => (hf φ).symm

/-- *Stripping* (`f = ∧`) makes every in-context claim false at `w₀`, in particular `⊤`. -/
theorem stripping_fails {F : Filter Valuation} {S : Formula} {w0 : Valuation}
    (hS0 : S.eval w0 = false) : ¬ TracksAt F S w0 (fun s x => s && x) := by
  intro h
  have := (h Formula.top).2 (holdsIn_top F)
  simp [hS0] at this

/-- *Conditionalizing* (`f = →`) makes every in-context claim true at `w₀`.  In a proper
context it therefore wrongly reports `¬S` as holding. -/
theorem conditionalizing_fails {F : Filter Valuation} (hF : Proper F) {S : Formula}
    {w0 : Valuation} (hS : HoldsIn F S) (hS0 : S.eval w0 = false) :
    ¬ TracksAt F S w0 (fun s x => !s || x) :=
  no_truthFunctional_eternal_reading hF hS hS0 _

/-- **The properness hypothesis is needed.**  An improper context proves everything, so
conditionalizing (`S → φ`, true at `w₀` for every `φ` since `S` is false there) tracks
in-context truth exactly.  This is the paper's rope remark after Thm 2.1. -/
theorem tracksAt_conditional_of_not_proper {F : Filter Valuation} (hF : ¬ Proper F)
    {S : Formula} {w0 : Valuation} (hS0 : S.eval w0 = false) :
    TracksAt F S w0 (fun s x => !s || x) := by
  intro φ
  have hall : HoldsIn F φ := (holdsIn_bot_iff.2 hF).mono fun u hu => by simp at hu
  simp [hS0, hall]

/-- Thm 2.1 for a single designated idealized world `w_c` with `S` true at `w_c`. -/
theorem no_eternal_reading_pure {wc w0 : Valuation} {S : Formula} (hS : S.eval wc = true)
    (hS0 : S.eval w0 = false) (f : Bool → Bool → Bool) :
    ¬ ∀ φ : Formula, (φ.eval wc = true ↔ f (S.eval w0) (φ.eval w0) = true) := by
  intro h
  apply no_truthFunctional_eternal_reading (proper_pure wc) (holdsIn_pure.2 hS) hS0 f
  intro φ
  rw [holdsIn_pure]
  exact (h φ).symm

/-- Thm 2.1 for in-context truth as truth in all worlds of a nonempty model class `K` in which
the stipulation `S` holds. -/
theorem no_eternal_reading_modelClass {K : Set Valuation} (hK : K.Nonempty) {S : Formula}
    {w0 : Valuation} (hS : ∀ u ∈ K, S.eval u = true) (hS0 : S.eval w0 = false)
    (f : Bool → Bool → Bool) :
    ¬ ∀ φ : Formula, ((∀ u ∈ K, φ.eval u = true) ↔ f (S.eval w0) (φ.eval w0) = true) := by
  intro h
  apply no_truthFunctional_eternal_reading (proper_principal_iff.2 hK)
    (holdsIn_principal.2 hS) hS0 f
  intro φ
  rw [holdsIn_principal]
  exact (h φ).symm

/-- **A concrete DEF instance** (cf. T3 Prop 1.6(a)).  Read atom `0` as "`p_atm = 0`".  At the
actual point `w₀ = (all false)` it is false.  The DEF child of the root deforms `D = {0}`
toward the ideal value `true` under limit semantics.  Then:
* both contexts are proper;
* the child proves `p₀` and the root proves `¬p₀`;
* the undeformed datum `¬p₁` is imported (Lemma 1.8(a));
* no truth-functional reading tracks truth in the child (Thm 2.1). -/
theorem patm_example :
    let w0 : Valuation := fun _ => false
    let c := defFilter {0} (pure w0) (pure fun _ => true)
    Proper (pure w0) ∧ Proper c ∧ HoldsIn c (var 0) ∧ HoldsIn (pure w0) (neg (var 0)) ∧
      HoldsIn c (neg (var 1)) ∧ ∀ f, ¬ TracksAt c (var 0) w0 f := by
  intro w0 c
  have hc : c = pure (deform {0} w0 fun _ => true) := defFilter_pure_pure _ _ _
  have hS : HoldsIn c (var 0) := by
    rw [hc, holdsIn_pure]; simp [deform]
  refine ⟨proper_pure _, ?_, hS, ?_, ?_, ?_⟩
  · rw [hc]; exact proper_pure _
  · rw [holdsIn_pure]; simp [w0]
  · refine import_sound (dStable_of_disjoint ?_) ?_
    · intro n hn; simp [Formula.atoms] at hn; simp [hn]
    · rw [holdsIn_pure]; simp [w0]
  · intro f
    refine no_truthFunctional_eternal_reading ?_ hS (by simp [w0]) f
    rw [hc]; exact proper_pure _

end Eternal

/-! ## Part 2. T3 Theorem 1.9 (reductio hygiene) -/

section Hygiene

/-- A reductio of `A` from the imported fragment `K` with the rule instances `R`: a step
derivation of `⊥` from `K ∪ {A}` (T3 §1.4).  Accepting it yields `c ⊩ ¬A`. -/
def Refutes (R : Set (Step Formula)) (K : Set Formula) (A : Formula) : Prop :=
  Formula.bot ∈ Cl R (insert A K)

/-- **T3 Thm 1.9(b).**  If the imported fragment is `R`-inconsistent, every sentence has a
reductio, in particular both `A` and `¬A`. -/
theorem refutes_of_inconsistent {R : Set (Step Formula)} {K : Set Formula}
    (hK : Formula.bot ∈ Cl R K) (A : Formula) : Refutes R K A :=
  Cl_mono_base (Set.subset_insert A K) hK

/-! ### (c) The three-premise example `K = {A → q, ¬A → q, ¬q}` -/

/-- The imported fragment `K = {A → q, ¬A → q, ¬q}` of T3 Thm 1.9(c). -/
def hygK (A q : Formula) : Set Formula := {imp A q, imp (neg A) q, neg q}

/-- `K` is unsatisfiable, for all formulas `A` and `q`. -/
theorem hygiene_K_unsat (A q : Formula) : ¬ Satisfiable (hygK A q) := by
  rintro ⟨v, hv⟩
  have h1 := hv (imp A q) (by simp [hygK])
  have h2 := hv (imp (neg A) q) (by simp [hygK])
  have h3 := hv (neg q) (by simp [hygK])
  simp only [eval_imp, eval_neg] at h1 h2 h3
  cases hA : A.eval v <;> cases hq : q.eval v <;> simp_all

/-- The used premises of `D_A`, `{A → q, ¬q}`, are satisfiable (atoms; `q` and `A` false). -/
theorem hygiene_K1_sat (a b : ℕ) : Satisfiable {imp (var a) (var b), neg (var b)} :=
  ⟨fun _ => false, by intro ψ hψ; simp at hψ; rcases hψ with rfl | rfl <;> simp⟩

/-- The used premises of `D_{¬A}`, `{¬A → q, ¬q}`, are satisfiable for distinct atoms
(`A` true, `q` false). -/
theorem hygiene_K2_sat {a b : ℕ} (hab : a ≠ b) :
    Satisfiable {imp (neg (var a)) (var b), neg (var b)} :=
  ⟨fun n => decide (n = a), by
    intro ψ hψ; simp at hψ; rcases hψ with rfl | rfl <;> simp [Ne.symm hab]⟩

/-- `{A → q, ¬q}` becomes unsatisfiable once the supposition `A` is added. -/
theorem hygiene_K1_supp_unsat (A q : Formula) :
    ¬ Satisfiable (insert A ({imp A q, neg q} : Set Formula)) := by
  rintro ⟨v, hv⟩
  simp only [satisfies_insert, satisfies_singleton, eval_imp, eval_neg] at hv
  obtain ⟨hA, h1, h2⟩ := hv
  simp_all

/-- `{¬A → q, ¬q}` becomes unsatisfiable once the supposition `¬A` is added. -/
theorem hygiene_K2_supp_unsat (A q : Formula) :
    ¬ Satisfiable (insert (neg A) ({imp (neg A) q, neg q} : Set Formula)) :=
  hygiene_K1_supp_unsat (neg A) q

/-- Classically, `{A → q, ¬q} ⊨ ¬A` and `{¬A → q, ¬q} ⊨ A`; so `K ⊨ ¬A` and `K ⊨ A`. -/
theorem hygiene_K_proves_both (A q : Formula) :
    SemCons {imp A q, neg q} (neg A) ∧ SemCons {imp (neg A) q, neg q} A ∧
      SemCons (hygK A q) (neg A) ∧ SemCons (hygK A q) A := by
  have hK : SemCons (hygK A q) Formula.bot :=
    SemCons.bot_iff_not_satisfiable.2 (hygiene_K_unsat A q)
  refine ⟨?_, ?_, SemCons.of_bot hK _, SemCons.of_bot hK _⟩
  · intro v hv
    simp only [satisfies_insert, satisfies_singleton, eval_imp, eval_neg] at hv
    cases hA : A.eval v <;> simp_all
  · intro v hv
    simp only [satisfies_insert, satisfies_singleton, eval_imp, eval_neg] at hv
    cases hA : A.eval v <;> simp_all

/-! ### Reductio derivations as data -/

/-- The data of a reductio derivation that a *derivation-local* test may inspect: the rule
instances used, the premises used, and the supposition.  The conclusion is `¬supp`. -/
structure Reductio where
  /-- The rule instances (steps) used. -/
  rules : Finset (Step Formula)
  /-- The premises used (a finite part of the imported fragment). -/
  prem : Finset Formula
  /-- The supposition `A` (the reductio concludes `¬A`). -/
  supp : Formula

namespace Reductio

/-- The conclusion `¬A` of the reductio. -/
def concl (D : Reductio) : Formula := neg D.supp

/-- The derivation is correct: `⊥` is derivable from `prem ∪ {supp}` with the steps used. -/
def Valid (D : Reductio) : Prop := Refutes ↑D.rules ↑D.prem D.supp

/-- Every rule instance used is classically sound. -/
def SoundRules (D : Reductio) : Prop := (↑D.rules : Set (Step Formula)) ⊆ SemSound

/-- A valid reductio with classically sound steps refutes its supposition classically:
`prem ∪ {supp}` is unsatisfiable. -/
theorem unsat_of_valid {D : Reductio} (hv : D.Valid) (hs : D.SoundRules) :
    ¬ Satisfiable (insert D.supp (↑D.prem : Set Formula)) :=
  SemCons.bot_iff_not_satisfiable.1 (Cl_subset_Cn2 hs _ hv)

end Reductio

/-- Modus ponens instance `A, A → q / q`. -/
def mpStep (A q : Formula) : Step Formula := ⟨{A, imp A q}, q⟩

/-- `¬`-elimination instance `q, ¬q / ⊥`. -/
def negElimStep (q : Formula) : Step Formula := ⟨{q, neg q}, Formula.bot⟩

theorem mpStep_sound (A q : Formula) : mpStep A q ∈ SemSound := by
  intro v hv
  simp only [mpStep, Finset.coe_insert, Finset.coe_singleton, satisfies_insert,
    satisfies_singleton, eval_imp] at hv
  obtain ⟨hA, h⟩ := hv
  show q.eval v = true
  simpa [hA] using h

theorem negElimStep_sound (q : Formula) : negElimStep q ∈ SemSound := by
  intro v hv
  simp only [negElimStep, Finset.coe_insert, Finset.coe_singleton, satisfies_insert,
    satisfies_singleton, eval_neg] at hv
  obtain ⟨hq, h⟩ := hv
  simp [hq] at h

/-- The reductio `D_A` of `A` from `{A → q, ¬q}`: `A, A → q / q`, then `q, ¬q / ⊥`.
The reductio `D_{¬A}` of `¬A` from `{¬A → q, ¬q}` is `DA (¬A) q`. -/
def DA (A q : Formula) : Reductio where
  rules := {mpStep A q, negElimStep q}
  prem := {imp A q, neg q}
  supp := A

theorem DA_valid (A q : Formula) : (DA A q).Valid := by
  unfold Reductio.Valid Refutes
  set R : Set (Step Formula) := ↑(DA A q).rules
  set B : Set Formula := insert (DA A q).supp ↑(DA A q).prem
  have hA : A ∈ Cl R B := subset_Cl (by simp [B, DA])
  have hAq : imp A q ∈ Cl R B := subset_Cl (by simp [B, DA])
  have hnq : neg q ∈ Cl R B := subset_Cl (by simp [B, DA])
  have hq : q ∈ Cl R B := by
    have := concl_mem_Cl (A := R) (B := B) (s := mpStep A q) (by simp [R, DA]) (by
      intro x hx
      simp only [mpStep, Finset.coe_insert, Finset.coe_singleton, Set.mem_insert_iff,
        Set.mem_singleton_iff] at hx
      rcases hx with rfl | rfl
      · exact hA
      · exact hAq)
    simpa [mpStep] using this
  have := concl_mem_Cl (A := R) (B := B) (s := negElimStep q) (by simp [R, DA]) (by
    intro x hx
    simp only [negElimStep, Finset.coe_insert, Finset.coe_singleton, Set.mem_insert_iff,
      Set.mem_singleton_iff] at hx
    rcases hx with rfl | rfl
    · exact hq
    · exact hnq)
  simpa [negElimStep] using this

theorem DA_soundRules (A q : Formula) : (DA A q).SoundRules := by
  intro s hs
  simp only [DA, Finset.coe_insert, Finset.coe_singleton, Set.mem_insert_iff,
    Set.mem_singleton_iff] at hs
  rcases hs with rfl | rfl
  · exact mpStep_sound A q
  · exact negElimStep_sound q

/-- Both reductios use only premises from `K`. -/
theorem DA_prem_subset (A q : Formula) : (↑(DA A q).prem : Set Formula) ⊆ hygK A q := by
  intro x hx
  simp only [DA, Finset.coe_insert, Finset.coe_singleton, Set.mem_insert_iff,
    Set.mem_singleton_iff] at hx
  rcases hx with rfl | rfl <;> simp [hygK]

theorem DnA_prem_subset (A q : Formula) : (↑(DA (neg A) q).prem : Set Formula) ⊆ hygK A q := by
  intro x hx
  simp only [DA, Finset.coe_insert, Finset.coe_singleton, Set.mem_insert_iff,
    Set.mem_singleton_iff] at hx
  rcases hx with rfl | rfl <;> simp [hygK]

/-- The conclusions `¬A` and `¬¬A` of the two reductios are jointly unsatisfiable. -/
theorem DA_DnA_concl_unsat (A q : Formula) :
    ¬ Satisfiable {(DA A q).concl, (DA (neg A) q).concl} := by
  rintro ⟨v, hv⟩
  simp only [Reductio.concl, DA, satisfies_insert, satisfies_singleton, eval_neg] at hv
  obtain ⟨h1, h2⟩ := hv
  simp_all

/-- **T3 Theorem 1.9(c) (derivation-local tests are not enough).**  Let `A = p_a` and
`q = p_b` be distinct atoms and `K = {A → q, ¬A → q, ¬q}`.  Let `T` be any test that is a
function of the derivation alone (rule instances used, premises used, supposition) and that
accepts every valid reductio with sound steps from a consistent (satisfiable) premise set.
Then:
* `K` is unsatisfiable;
* `D_A` and `D_{¬A}` are valid reductios that use only premises from `K`;
* `T` accepts both;
* their conclusions `¬A` and `¬¬A` are jointly unsatisfiable. -/
theorem derivation_local_test_accepts_both {a b : ℕ} (hab : a ≠ b) (T : Reductio → Prop)
    (hT : ∀ D : Reductio, D.Valid → D.SoundRules → Satisfiable (↑D.prem : Set Formula) → T D) :
    ¬ Satisfiable (hygK (var a) (var b)) ∧
      (DA (var a) (var b)).Valid ∧ (DA (neg (var a)) (var b)).Valid ∧
      (↑(DA (var a) (var b)).prem : Set Formula) ⊆ hygK (var a) (var b) ∧
      (↑(DA (neg (var a)) (var b)).prem : Set Formula) ⊆ hygK (var a) (var b) ∧
      T (DA (var a) (var b)) ∧ T (DA (neg (var a)) (var b)) ∧
      ¬ Satisfiable {(DA (var a) (var b)).concl, (DA (neg (var a)) (var b)).concl} := by
  refine ⟨hygiene_K_unsat _ _, DA_valid _ _, DA_valid _ _, DA_prem_subset _ _,
    DnA_prem_subset _ _, ?_, ?_, DA_DnA_concl_unsat _ _⟩
  · refine hT _ (DA_valid _ _) (DA_soundRules _ _) ?_
    simpa [DA] using hygiene_K1_sat a b
  · refine hT _ (DA_valid _ _) (DA_soundRules _ _) ?_
    simpa [DA] using hygiene_K2_sat hab

/-- Variant of `derivation_local_test_accepts_both` in which "sound reductio" is read
semantically: the test accepts every valid reductio whose premises are satisfiable but become
unsatisfiable when the supposition is added.  By `Reductio.unsat_of_valid`, this hypothesis
implies the one used above. -/
theorem derivation_local_test_accepts_both' {a b : ℕ} (hab : a ≠ b) (T : Reductio → Prop)
    (hT : ∀ D : Reductio, D.Valid → ¬ Satisfiable (insert D.supp (↑D.prem : Set Formula)) →
      Satisfiable (↑D.prem : Set Formula) → T D) :
    ¬ Satisfiable (hygK (var a) (var b)) ∧
      T (DA (var a) (var b)) ∧ T (DA (neg (var a)) (var b)) ∧
      ¬ Satisfiable {(DA (var a) (var b)).concl, (DA (neg (var a)) (var b)).concl} := by
  obtain ⟨h1, -, -, -, -, h6, h7, h8⟩ := derivation_local_test_accepts_both hab T
    (fun D hv hs hsat => hT D hv (Reductio.unsat_of_valid hv hs) hsat)
  exact ⟨h1, h6, h7, h8⟩

/-! ### (d) A consistency certificate suffices -/

/-- **T3 Thm 1.9(d).**  Suppose a structure (valuation) `N` satisfies the imported fragment
`K` and every rule instance in `R` (`N ⊨ ⋀Π → j`).  Then every `A` with a reductio from `K`
is false in `N`. -/
theorem certificate_refutes_false {R : Set (Step Formula)} {K : Set Formula} {A : Formula}
    {N : Valuation} (hK : Satisfies N K)
    (hR : ∀ s ∈ R, Satisfies N ↑s.prem → s.concl.eval N = true) (h : Refutes R K A) :
    A.eval N = false := by
  by_contra hA
  rw [Bool.not_eq_false] at hA
  have hsub : Cl R (insert A K) ⊆ {φ | φ.eval N = true} := by
    refine Cl_subset ?_ ?_
    · intro φ hφ
      rcases hφ with rfl | hφ
      · exact hA
      · exact hK φ hφ
    · intro s hs hprem
      exact hR s hs fun ψ hψ => hprem hψ
  have := hsub h
  simp at this

/-- With a certificate, no `A` has reductios of both `A` and `¬A`. -/
theorem certificate_not_both {R : Set (Step Formula)} {K : Set Formula} {N : Valuation}
    (hK : Satisfies N K) (hR : ∀ s ∈ R, Satisfies N ↑s.prem → s.concl.eval N = true)
    (A : Formula) : ¬ (Refutes R K A ∧ Refutes R K (neg A)) := by
  rintro ⟨h1, h2⟩
  have e1 := certificate_refutes_false hK hR h1
  have e2 := certificate_refutes_false hK hR h2
  simp [e1] at e2

/-- **T3 Thm 1.9(d), counterexample.**  The certificate must also satisfy the rule instances.
Take `K = {¬q}`, which is satisfiable, and the rule instances `/q` (zero premises; sound in any
context where `q` holds) and `q, ¬q / ⊥`.  Then every `A` and every `¬A` has a reductio. -/
theorem certificate_rules_needed (b : ℕ) :
    Satisfiable ({neg (var b)} : Set Formula) ∧
      ∀ A : Formula, Refutes {⟨∅, var b⟩, negElimStep (var b)} {neg (var b)} A ∧
        Refutes {⟨∅, var b⟩, negElimStep (var b)} {neg (var b)} (neg A) := by
  refine ⟨⟨fun _ => false, by simp⟩, fun A => ⟨?_, ?_⟩⟩ <;>
  · apply refutes_of_inconsistent
    have hq : var b ∈ Cl ({⟨∅, var b⟩, negElimStep (var b)} : Set (Step Formula))
        {neg (var b)} := by
      have := concl_mem_Cl (A := ({⟨∅, var b⟩, negElimStep (var b)} : Set (Step Formula)))
        (B := {neg (var b)}) (s := ⟨∅, var b⟩) (by simp) (by simp)
      simpa using this
    have := concl_mem_Cl (A := ({⟨∅, var b⟩, negElimStep (var b)} : Set (Step Formula)))
      (B := {neg (var b)}) (s := negElimStep (var b)) (by simp) (by
        intro x hx
        simp only [negElimStep, Finset.coe_insert, Finset.coe_singleton, Set.mem_insert_iff,
          Set.mem_singleton_iff] at hx
        rcases hx with rfl | rfl
        · exact hq
        · exact subset_Cl rfl)
    simpa [negElimStep] using this

/-! ### (a) Soundness in the filter semantics -/

/-- A rule instance is `c`-sound if `c ⊨ ⋀Π → j`, i.e. the set of points where it holds is in
the context's filter. -/
def StepHoldsIn (F : Filter Valuation) (s : Step Formula) : Prop :=
  {u | Satisfies u ↑s.prem → s.concl.eval u = true} ∈ F

/-- **T3 Thm 1.9(a) (toy, filter semantics).**  Suppose every rule instance in `R` is
`c`-sound and `c ⊨ K`.  Then every reductio of `A` from `K` yields a true `¬A` in `c`.  The
proof is the existence half of 1.9(d).  The finitely many truth sets of the premises and of
the instances used lie in `F`.  Every point of their intersection is a certificate, so it
falsifies `A` by `certificate_refutes_false`. -/
theorem refutation_sound_in_context {F : Filter Valuation} {R : Set (Step Formula)}
    {K : Set Formula} {A : Formula} (hK : ∀ ψ ∈ K, HoldsIn F ψ)
    (hR : ∀ s ∈ R, StepHoldsIn F s) (h : Refutes R K A) : HoldsIn F (neg A) := by
  classical
  obtain ⟨R₀, B₀, hR₀, hB₀, hd⟩ := exists_finite_of_mem_Cl h
  set K₀ : Finset Formula := B₀.erase A
  have hK₀ : (↑K₀ : Set Formula) ⊆ K := by
    intro ψ hψ
    rw [Finset.coe_erase] at hψ
    rcases hB₀ hψ.1 with h' | h'
    · exact absurd h' hψ.2
    · exact h'
  have hd' : Refutes ↑R₀ ↑K₀ A := by
    refine Cl_mono_base ?_ hd
    intro ψ hψ
    by_cases hψA : ψ = A
    · exact Or.inl hψA
    · exact Or.inr (by rw [Finset.coe_erase]; exact ⟨hψ, hψA⟩)
  have hmemR : (⋂ s ∈ R₀, {u | Satisfies u ↑s.prem → s.concl.eval u = true}) ∈ F :=
    (Filter.biInter_finset_mem R₀).2 fun s hs => hR s (hR₀ hs)
  have hmemK : (⋂ ψ ∈ K₀, truthSet ψ) ∈ F :=
    (Filter.biInter_finset_mem K₀).2 fun ψ hψ => hK ψ (hK₀ hψ)
  refine Filter.mem_of_superset (Filter.inter_mem hmemR hmemK) ?_
  rintro u ⟨huR, huK⟩
  simp only [Set.mem_iInter, Set.mem_setOf_eq] at huR
  simp only [Set.mem_iInter, mem_truthSet] at huK
  have := certificate_refutes_false (R := ↑R₀) (K := ↑K₀) (N := u)
    (fun ψ hψ => huK ψ hψ) (fun s hs hp => huR s hs hp) hd'
  simp [this]

/-- Hence a **proper** context with `c ⊨ K` and `c`-sound rule instances never refutes both
`A` and `¬A` (T3 §1.4: a properness witness is a certificate). -/
theorem proper_not_both_refuted {F : Filter Valuation} (hF : Proper F)
    {R : Set (Step Formula)} {K : Set Formula} (hK : ∀ ψ ∈ K, HoldsIn F ψ)
    (hR : ∀ s ∈ R, StepHoldsIn F s) (A : Formula) :
    ¬ (Refutes R K A ∧ Refutes R K (neg A)) := by
  rintro ⟨h1, h2⟩
  exact not_holdsIn_neg_of_holdsIn hF (refutation_sound_in_context hK hR h1)
    (refutation_sound_in_context hK hR h2)

end Hygiene

/-! ## Part 3. T2 Proposition 7.1 (mis-designation forces global sub-classicality) -/

section Misdesignation

variable {C : ConsOp Formula}

/-- `C` is `𝒜`-coherent (T2 §1): `A ⊬_C ⊥` for every designated context `A ∈ 𝒜`. -/
def DesignatedCoherent (C : ConsOp Formula) (𝒜 : Set (Set Formula)) : Prop :=
  ∀ A ∈ 𝒜, Consistent C A

/-- If `C ⊇ C₂`, every context containing `α` and `¬α` has `C`-closure `Fm` (everything).
Structurality is not needed. -/
theorem closure_eq_univ_of_contradictory (h2 : Cn2 ≤ C) {A : Set Formula} {α : Formula}
    (hα : α ∈ A) (hnα : neg α ∈ A) : C A = Set.univ := by
  have hunsat : ¬ Satisfiable A := by
    rintro ⟨v, hv⟩
    have h1 := hv α hα
    have h2 := hv (neg α) hnα
    simp [h1] at h2
  exact Set.eq_univ_of_univ_subset ((Cn2_eq_univ_iff.2 hunsat) ▸ h2 A)

/-- If `C ⊇ C₂`, every classically inconsistent context is `C`-trivial. -/
theorem closure_eq_univ_of_unsat (h2 : Cn2 ≤ C) {A : Set Formula} (hA : ¬ Satisfiable A) :
    C A = Set.univ :=
  Set.eq_univ_of_univ_subset ((Cn2_eq_univ_iff.2 hA) ▸ h2 A)

/-- Hence a `C` that is consistent (`⊥ ∉ C A`) on a classically inconsistent context `A`
cannot extend `C₂`. -/
theorem not_Cn2_le_of_consistent_unsat {A : Set Formula} (hA : ¬ Satisfiable A)
    (hC : Consistent C A) : ¬ Cn2 ≤ C := by
  intro h2
  apply hC
  rw [closure_eq_univ_of_unsat h2 hA]
  trivial

/-- The same for coherence read as non-triviality (`C A ≠ Fm`). -/
theorem not_Cn2_le_of_coherent_unsat {A : Set Formula} (hA : ¬ Satisfiable A)
    (hC : C.Coherent A) : ¬ Cn2 ≤ C :=
  fun h2 => hC (closure_eq_univ_of_unsat h2 hA)

/-- The task's form: a structural `C` that is coherent on a designated context containing `α`
and `¬α` cannot extend `C₂`.  Structurality is not used. -/
theorem not_Cn2_le_of_coherent_contradictory (_hCs : Structural C) {A : Set Formula}
    {α : Formula} (hα : α ∈ A) (hnα : neg α ∈ A) (hC : C.Coherent A) : ¬ Cn2 ≤ C :=
  fun h2 => hC (closure_eq_univ_of_contradictory h2 hα hnα)

/-- **T2 Prop 7.1(a), first claim.**  If `C` is `𝒜`-coherent and some designated `A ∈ 𝒜` is
classically inconsistent, then `C ⊉ C₂`.  The paper assumes `C` structural; that hypothesis
is not needed here. -/
theorem misdesignation_not_Cn2_le {𝒜 : Set (Set Formula)} (hC : DesignatedCoherent C 𝒜)
    {A : Set Formula} (hA𝒜 : A ∈ 𝒜) (hA : ¬ Satisfiable A) : ¬ Cn2 ≤ C :=
  not_Cn2_le_of_consistent_unsat hA (hC A hA𝒜)

/-- **T2 Prop 7.1(a), second claim, instance level.**  If `A ⊬_C ⊥`, then every step
derivation of `⊥` from `A`, for example a CPC derivation, uses some step `(Π, j) ∈ R` that is
not `C`-valid: `j ∉ C Π`. -/
theorem exists_invalid_step {A : Set Formula} (hC : Consistent C A) {R : Set (Step Formula)}
    (hR : Formula.bot ∈ Cl R A) : ∃ s ∈ R, s.concl ∉ C ↑s.prem := by
  by_contra hcon
  push Not at hcon
  exact hC (ClOp_le_iff.2 hcon A hR)

/-- **T2 Prop 7.1(a), second claim, schema level.**  Let `C` be structural and `A ⊬_C ⊥`.
Suppose the steps of a derivation of `⊥` from `A` are substitution instances of schemata `D`
(`R ⊆ substClosure D`).  Then some schema `s ∈ D`, i.e. its most general instance, is not
`C`-valid.  So the learner loses that rule *as a uniform schema*, everywhere. -/
theorem exists_invalid_schema (hCs : Structural C) {A : Set Formula} (hC : Consistent C A)
    {D R : Set (Step Formula)} (hRD : R ⊆ substClosure D) (hR : Formula.bot ∈ Cl R A) :
    ∃ s ∈ D, s.concl ∉ C ↑s.prem := by
  by_contra hcon
  push Not at hcon
  have hle := ClOp_substClosure_le hCs hcon
  exact hC (hle A (Cl_mono_rules hRD hR))

/-- The substitution `p ↦ α` (other atoms fixed). -/
def substAt (p : ℕ) (α : Formula) : Subst := fun n => if n = p then α else var n

theorem image_substAt_pair (p : ℕ) (α : Formula) :
    Formula.subst (substAt p α) '' ({var p, neg (var p)} : Set Formula) = {α, neg α} := by
  simp [Set.image_insert_eq, substAt]

/-- **T2 Prop 7.1(b).**  Let `C` be structural and consistent on a (designated) context `A`
that contains `α` and `¬α`.  Then `p, ¬p ⊬_C ⊥` for every atom `p`: `C` is paraconsistent
at the atomic level, everywhere. -/
theorem atomic_paraconsistent (hCs : Structural C) {A : Set Formula} (hC : Consistent C A)
    {α : Formula} (hα : α ∈ A) (hnα : neg α ∈ A) (p : ℕ) :
    Consistent C {var p, neg (var p)} := by
  intro h
  have h' := hCs.mem_subst h (substAt p α)
  rw [image_substAt_pair] at h'
  apply hC
  have hsub : ({α, neg α} : Set Formula) ⊆ A := by
    intro x hx
    rcases hx with rfl | rfl
    · exact hα
    · exact hnα
  simpa using C.mono hsub h'

/-- **T2 Prop 7.1(b), non-triviality form.**  If a structural `C` is coherent (non-trivial) on
a context containing `α` and `¬α`, then `C {p, ¬p} ≠ Fm` for every atom `p`. -/
theorem atomic_nontrivial (hCs : Structural C) {A : Set Formula} (hC : C.Coherent A)
    {α : Formula} (hα : α ∈ A) (hnα : neg α ∈ A) (p : ℕ) :
    C.Coherent {var p, neg (var p)} := by
  intro h
  apply hC
  have hsub : ({α, neg α} : Set Formula) ⊆ A := by
    intro x hx
    rcases hx with rfl | rfl
    · exact hα
    · exact hnα
  refine Set.eq_univ_of_forall fun φ => ?_
  -- substitute `p ↦ α` and the fresh atom `p+1 ↦ φ`
  let σ : Subst := fun n => if n = p then α else if n = p + 1 then φ else var n
  have hmem : var (p + 1) ∈ C {var p, neg (var p)} := by rw [h]; trivial
  have h' := hCs.mem_subst hmem σ
  have himg : Formula.subst σ '' ({var p, neg (var p)} : Set Formula) = {α, neg α} := by
    simp [Set.image_insert_eq, σ]
  rw [himg] at h'
  have hφ : (var (p + 1)).subst σ = φ := by simp [σ]
  rw [hφ] at h'
  exact C.mono hsub h'

end Misdesignation

end Contexts

end InfLearn

/-! ## Axiom audit -/

-- Part 1 (T3 §1–2, propositional toy)
#print axioms InfLearn.Contexts.cn2_closed_ThIn
#print axioms InfLearn.Contexts.consistent_ThIn_iff
#print axioms InfLearn.Contexts.holdsIn_sup_iff
#print axioms InfLearn.Contexts.import_sound
#print axioms InfLearn.Contexts.eternal_reading_witnesses
#print axioms InfLearn.Contexts.no_truthFunctional_eternal_reading
#print axioms InfLearn.Contexts.not_exists_truthFunctional_reading
#print axioms InfLearn.Contexts.stripping_fails
#print axioms InfLearn.Contexts.conditionalizing_fails
#print axioms InfLearn.Contexts.tracksAt_conditional_of_not_proper
#print axioms InfLearn.Contexts.no_eternal_reading_pure
#print axioms InfLearn.Contexts.no_eternal_reading_modelClass
#print axioms InfLearn.Contexts.patm_example
-- Part 2 (T3 Thm 1.9)
#print axioms InfLearn.Contexts.refutes_of_inconsistent
#print axioms InfLearn.Contexts.hygiene_K_unsat
#print axioms InfLearn.Contexts.hygiene_K1_sat
#print axioms InfLearn.Contexts.hygiene_K2_sat
#print axioms InfLearn.Contexts.hygiene_K1_supp_unsat
#print axioms InfLearn.Contexts.hygiene_K2_supp_unsat
#print axioms InfLearn.Contexts.hygiene_K_proves_both
#print axioms InfLearn.Contexts.DA_valid
#print axioms InfLearn.Contexts.DA_soundRules
#print axioms InfLearn.Contexts.derivation_local_test_accepts_both
#print axioms InfLearn.Contexts.derivation_local_test_accepts_both'
#print axioms InfLearn.Contexts.certificate_refutes_false
#print axioms InfLearn.Contexts.certificate_not_both
#print axioms InfLearn.Contexts.certificate_rules_needed
#print axioms InfLearn.Contexts.refutation_sound_in_context
#print axioms InfLearn.Contexts.proper_not_both_refuted
-- Part 3 (T2 Prop 7.1)
#print axioms InfLearn.Contexts.closure_eq_univ_of_contradictory
#print axioms InfLearn.Contexts.not_Cn2_le_of_consistent_unsat
#print axioms InfLearn.Contexts.not_Cn2_le_of_coherent_unsat
#print axioms InfLearn.Contexts.not_Cn2_le_of_coherent_contradictory
#print axioms InfLearn.Contexts.misdesignation_not_Cn2_le
#print axioms InfLearn.Contexts.exists_invalid_step
#print axioms InfLearn.Contexts.exists_invalid_schema
#print axioms InfLearn.Contexts.atomic_paraconsistent
#print axioms InfLearn.Contexts.atomic_nontrivial
