#!/usr/bin/env python3
"""Merge bib/*.bib (except all.bib) into bib/all.bib, keeping the first entry for each key.
Reports keys whose duplicate entries differ in title, so they can be reconciled by hand."""
import re, glob, os
here = os.path.dirname(os.path.abspath(__file__))
entries, order, conflicts = {}, [], []
for f in sorted(glob.glob(os.path.join(here, 'bib', '*.bib'))):
    if f.endswith('all.bib'):
        continue
    text = open(f, encoding='utf-8').read()
    # split at '@' entries at line start
    for m in re.finditer(r'(?ms)^@(\w+)\s*\{\s*([^,\s]+)\s*,(.*?)(?=^@|\Z)', text):
        kind, key, body = m.group(1), m.group(2), m.group(3)
        full = '@%s{%s,%s' % (kind, key, body.rstrip())
        if key in entries:
            t_old = re.search(r'title\s*=\s*[{"](.*?)[}"]\s*,?\s*$', entries[key], re.M | re.I)
            t_new = re.search(r'title\s*=\s*[{"](.*?)[}"]\s*,?\s*$', full, re.M | re.I)
            if t_old and t_new and t_old.group(1).lower().strip('{}') != t_new.group(1).lower().strip('{}'):
                conflicts.append((key, os.path.basename(f)))
            continue
        entries[key] = full
        order.append(key)
with open(os.path.join(here, 'bib', 'all.bib'), 'w', encoding='utf-8') as out:
    out.write('% Generated by merge_bib.py from bib/*.bib; do not edit by hand.\n\n')
    for k in order:
        out.write(entries[k].rstrip() + '\n\n')
print(f'{len(order)} entries; {len(conflicts)} title conflicts: {conflicts[:20]}')
