export const meta = {
  name: 'schemas-write-B',
  description: 'Draft paper sections ZFC and induction, many schemas without labels, and experiments (with appendices) from the refereed research notes',
  phases: [{ title: 'Write', detail: 'one writer per section' }],
}
const P = '/home/user/AI-works/axiom-schemas/paper'
const R = '/home/user/AI-works/axiom-schemas/research'
const SECTIONS = [
  { key: 'zf', files: 'sections/zfc.tex and sections/app-zfc.tex', spec: 'Section 5 of OUTLINE.md (ZFC schemas and PA induction, Q2).' },
  { key: 'many', files: 'sections/many.tex and sections/app-many.tex', spec: 'Section 6 of OUTLINE.md (many schemas without labels, DTRC, Q3).' },
  { key: 'exp', files: 'sections/experiments.tex and sections/app-experiments.tex', spec: 'Section 7 of OUTLINE.md (experiments). Also read /home/user/AI-works/axiom-schemas/code/README.md and code/results/*.md; check numbers against the results files, not only the notes.' },
]
const SCHEMA = { type: 'object', properties: { files: { type: 'array', items: { type: 'string' } }, pages_main: { type: 'number' }, pages_app: { type: 'number' }, labels_defined: { type: 'array', items: { type: 'string' } }, compiles: { type: 'boolean' }, notes: { type: 'string', description: 'deviations, unresolved issues, things other sections must know' } }, required: ['files', 'compiles', 'labels_defined', 'notes'] }
const prompt = s => `You are writing one section (plus its appendix) of a standalone research paper, "Learning Axioms and Axiom Schemas from Their Instances", in LaTeX. Read FIRST: ${P}/OUTLINE.md (your spec: ${s.spec}), ${P}/NOTATION.md (binding conventions, macros, label scheme, bib keys), ${P}/preamble.tex (macros; do not redefine), ${R}/00-brief.md. Then read the relevant research records fully (they are the ONLY sources of claims; use the FINAL notes and honour their verification logs and corrections): ${R}/tracks/single/notes-final.md, ${R}/tracks/cases/notes-final.md, ${R}/tracks/untagged/notes-final.md, ${R}/tracks/experiments/notes-final.md, and where relevant ${R}/prior/induction/*-notes.md and *-referee.md, ${R}/prior/pa-untagged/findings.txt, and the referee reports in each track directory. Write ${P}/${s.files}. Requirements: standalone and precise; every theorem-like environment carries \\status{...} and \\src{...}; main text gives statements, short proofs or proof ideas, and pointers to the appendix, which gives the full proofs (adapted from the notes, checked as you transcribe them — if you find an error, fix it if you can and record it in 'notes'); keep all hedges, conditions and caveats; do not overclaim; use only bib keys from bib/core.bib or add entries to ${P}/bib/${s.key}.bib (verify they are real; hedge uncertain ones). Use labels per the scheme; refer to other sections by these planned labels: sec:intro, sec:setting, sec:single, sec:univ, sec:zf, sec:many, sec:exp, sec:disc, app:setting, app:single, app:univ, app:zf, app:many, app:exp, app:ver (other sections are written in parallel; do not depend on their internal labels except these; if you need a specific result from another section, cite the section and name the result in words). The section file starts with \\section{...}\\label{sec:${s.key}}; the appendix file starts with \\section{...}\\label{app:${s.key}}. Figures are in ${P}/figures/ (refer to them as figures/name.png). Length: as in OUTLINE.md. When done, compile with: cd ${P} && ./test-section.sh <section-basename> <appendix-basename> (e.g. ./test-section.sh ${s.files.split(' ')[0].replace('sections/','').replace('.tex','')} ${s.files.split(' ')[2].replace('sections/','').replace('.tex','')}) and fix all LaTeX errors and undefined citations. Return the structured summary.`
phase('Write')
const res = await parallel(SECTIONS.map(s => () => agent(prompt(s), { label: `write:${s.key}`, phase: 'Write', schema: SCHEMA })))
return SECTIONS.map((s, i) => ({ key: s.key, result: res[i] }))
