export const meta = {
  name: 'schemas-write-C',
  description: 'Write introduction+abstract, discussion, and the verification appendix for the axiom-schema paper',
  phases: [{ title: 'Write', detail: 'intro+abstract, discussion, verification appendix' }],
}
const P = '/home/user/AI-works/axiom-schemas/paper'
const R = '/home/user/AI-works/axiom-schemas/research'
const COMMON = `You are writing part of a standalone research paper, "Learning Axioms and Axiom Schemas from Their Instances" (LaTeX, ${P}/main.tex). Read FIRST: ${P}/OUTLINE.md, ${P}/NOTATION.md, ${P}/preamble.tex, ${R}/00-brief.md (the commissioner's questions are quoted verbatim there), and ${P}/writer-notes.txt (notes from the section writers, incl. corrections they made and open items). Then read the drafted sections: ${P}/sections/setting.tex, single.tex, universal.tex, zfc.tex, many.tex, experiments.tex (and skim their appendices app-*.tex). The research records in ${R}/tracks/*/notes-final.md and referee.md, and ${R}/prior/ are the ground truth: never claim more than they establish; keep hedges and conditions. Refer to results by their actual labels in the section files (grep for \\label). Do not edit files other than yours. After writing, build the whole paper with: cd ${P} && ./build.sh — and make sure your files introduce no LaTeX errors, undefined references or citations (other people may be editing other files concurrently; if the build breaks because of someone else's file, say so in notes). The paper is a draft prepared by Claude (Anthropic) for Kaarel Hänni; publication is his decision. It is about learning for CHECKING (which axioms a community uses), not about building provers.`
const SCHEMA = { type: 'object', properties: { files: { type: 'array', items: { type: 'string' } }, notes: { type: 'string' } }, required: ['files', 'notes'] }
const JOBS = [
  { key: 'intro', prompt: `Write ${P}/sections/intro.tex (\\section{Introduction}\\label{sec:intro}, about 4-5 pages) and ${P}/sections/abstract.tex (\\begin{abstract}...\\end{abstract}, at most 250 words). The introduction must: state the motivation briefly (learning which inferences/axioms a community uses, from positive instances, as in the parent report \\citep{claude2026whatfollows}); quote the three questions; give the answers in brief, each precise and with pointers (\\cref to the main theorems): Q1 (universal axiom from instances: first-order pattern, anchors, rates; but what is learned is the instance schema; the omega-gap and the Tarski-Vaught criterion; capture and guards), Q2 (ZF schemas: all are Miller patterns, so pattern anti-unification and the determinate learner both work from two instances under (R)+(N); first-order learning depends on formulation and encoding, with explicit failures and the 'no finite union' theorem; Separation's freshness guard; PA induction as the contrast: not a Miller pattern but determinate; first-order and pattern learners fail; the determinate learner works), Q3 (many schemas without labels: a bound or negatives is needed; spare slots; the pigeonhole theorem; the DTRC method and its main theorem under refutation separation, residue, the ∀xφ case as a sound merge, depth relativization is necessary, complexity results, and what the experiments show including the failure exhibit); then a contributions list; what is NOT achieved (honest limits: separation is an assumption, refutation completeness, cost/hardness results, mistakes, rare targets, open problems); a reader's guide. Use a summary table if it helps (e.g. schema × class × anchor condition, or question × answer × theorem).` },
  { key: 'disc', prompt: `Write ${P}/sections/discussion.tex (\\section{Discussion}\\label{sec:disc}, about 3-4 pages): what the answers mean for the commissioner's broader project of learning inference rules (an instance schema vs a universal sentence; formulation-dependence of first-order learnability; why the pattern fragment matters; induction's derived occurrences; refutation as the source of labels; truth-soundness vs target-soundness of merges); relation to the literature (ILP and Plotkin/Reynolds anti-unification; higher-order anti-unification (Pfenning, Baumgartner-Kutsia-Levy-Villaret, Cerna-Kutsia survey); second-order matching (Huet-Lang); learning from positive data (Gold, Angluin, Wright, Motoki-Shinohara-Wright); MDL and the size principle; axiomatizability by schemas (Vaught, Ryll-Nardzewski); proof assistants' motives (Lean) and implicit substitution (Metamath)) — use only bib keys that exist in ${P}/bib/*.bib or add to ${P}/bib/disc.bib with hedges if unverified; consolidated open problems (collect from all sections' open problems and the tracks' notes-final 'Open problems'; list each with a pointer); limitations; scope statement (checking, not proving).` },
  { key: 'ver', prompt: `Write ${P}/sections/app-verification.tex (\\section{How the results were established}\\label{app:ver}, about 2-4 pages). Describe the process: research tracks (cases, single, untagged, experiments) plus prior refereed work on PA induction (${R}/prior/), each developed by one researcher, attacked by an adversarial referee with independent code and brute-force checks, then revised with a point-by-point verification log (files: ${R}/tracks/*/referee.md and the 'Verification log' sections of notes-final.md; prior: ${R}/prior/induction/*-referee.md); section writers re-checked proofs while transcribing (see ${P}/writer-notes.txt). Give a table of the substantive corrections made during verification and writing (refuted or withdrawn claims and conjectures, strengthened hypotheses): e.g. prior C8.3 true for DT° but false with nested arguments; C8.2 corrected from 8 to 4 minimal templates; C11 (linear escalations) refuted, Theta(N^2) instead; experiments' v1 E1 false for rigid parameters (alignment-complete Min); the claim 'PA mistakes merge only into valid templates' withdrawn (false sentence q_F accepted at budgets 80 and 400); v1 head-class caveat withdrawn; Thm on depth rebuilt via MRDP; Q1 capture instances (unguarded first-order verifier unsound outright); Prop C3' (Collection); single Thm E ground-template fixes; untagged Cor 3.3(b) hypothesis; writer-stage fixes (from writer-notes.txt). List results NOT independently refereed (added in revision, e.g. single Thm H, Prop E.2, F.9, F.10, D.7; untagged additions after referee; writer-stage extensions such as the alignment proposition for DT°) and remaining conjectures/open problems. Reproduction: code location (${P}/../code/, README, 'python3 -m pytest -q tests', 'sh run_all.sh' ~10 min), research notes location, scripts. Read ${R}/tracks/*/referee.md, the verification logs, ${R}/prior/induction/*-referee.md, and ${P}/writer-notes.txt.` },
]
phase('Write')
const res = await parallel(JOBS.map(j => () => agent(`${COMMON}\n\nYOUR JOB: ${j.prompt}\n\nReturn files written and notes (anything other sections must fix, inconsistencies you noticed between sections).`, { label: `write:${j.key}`, phase: 'Write', schema: SCHEMA })))
return JOBS.map((j, i) => ({ key: j.key, result: res[i] }))
