export const meta = {
  name: 'schemas-final-F',
  description: 'Align intro/abstract, discussion and verification appendix with the edited sections, then a fresh whole-paper consistency and fidelity pass with build',
  phases: [{ title: 'Align', detail: 'intro+abstract; discussion+verification appendix' }, { title: 'Final', detail: 'fresh whole-paper check, fixes, build' }],
}
const P = '/home/user/AI-works/axiom-schemas/paper'
const RV = '/home/user/AI-works/axiom-schemas/research/paper-review'
const R = '/home/user/AI-works/axiom-schemas/research'
const CTX = `Paper: ${P}/main.tex (sections in ${P}/sections/). The six core sections (setting, single, universal, zfc, many, experiments + appendices) were just edited after a whole-paper review; editors' reports with the changes that the introduction, abstract, discussion and verification appendix must now reflect are in ${RV}/edits/E1-results.txt and ${RV}/edits/E2-results.txt ('FOR FINAL' parts) and the full structured results in the workflow outputs summarized there; decisions in ${RV}/edits/DECISIONS.md; review reports ${RV}/review-*.md; conventions ${P}/NOTATION.md. Ground truth: ${R}/tracks/*/notes-final.md, referee.md, ${R}/prior/. Build only under the lock: cd ${P} && flock /tmp/claude-0/paper-build.lock ./build.sh.`
const SCHEMA = { type: 'object', properties: { changes: { type: 'array', items: { type: 'string' } }, remaining_issues: { type: 'string' }, build: { type: 'string' } }, required: ['changes', 'remaining_issues', 'build'] }
phase('Align')
const align = await parallel([
  () => agent(`${CTX}\n\nYOUR FILES: ${P}/sections/intro.tex and ${P}/sections/abstract.tex (edit only these). Bring them in line with the edited sections: apply every 'FOR FINAL' item that concerns the intro or abstract (e.g. omega-step wording — it holds in every model of true arithmetic, so do not say it fails in nonstandard models of PA; 'not derivable in general'; (Rich) qualifier on 'anchor iff events' and 'anchor has an lgg'; ReplS truth-soundness only on anchor data; separation 'proved for an ideal refuter' for the mixtures, computed for ZF/ZFC sampled pairs; sharing pass only for targets labelling a phase-one cluster; root specializations nine over L_A; capture guard corrections; results now in appendices referenced as such; Question 1/2/3 naming). Then re-read every claim in intro and abstract against the current section texts (grep labels, read the cited statements) and fix any mismatch or overclaim; keep the intro about 5 pages and the abstract at most 250 words. Make sure the answers to the three questions are stated crisply and correctly near the start. Build and fix any errors you introduced.`, { label: 'align:intro', phase: 'Align', schema: SCHEMA }),
  () => agent(`${CTX}\n\nYOUR FILES: ${P}/sections/discussion.tex, ${P}/sections/app-verification.tex and ${P}/bib/disc.bib (edit only these). Apply every 'FOR FINAL' item that concerns the discussion or the verification appendix (e.g. qualify 'separate PA, ZF and ZFC at small depth'; 'not derivable in general'; R-Delta0 only refutes every false instance for quantifier-free phi; sharing-pass open problem; the new conjecture conj:zf:root (two formal conjectures now); the alignment counterexample (rem:setting:alignfail) and the sharing-pass counterexample (ex:exp:share) and the ReplS non-anchor-pair correction and the 'nonstandard models' wording as corrections found in the paper review — add rows to the corrections table; the list of results not independently refereed must include material written or changed during the paper review (new proofs, ex:exp:share, rem:setting:alignfail, prop:single:union-esc, lem:univ:capcrit, conj:zf:root, ex:single:features, etc. — check the editors' reports); moved labels now in appendices). Also check every bib entry in disc.bib is real and relevant: for any entry you cannot verify with high confidence (e.g. recent arXiv papers found by web search), either verify it (WebFetch/WebSearch may be available) or remove the citation and the entry. Re-read every claim in the discussion against the current section texts; fix mismatches. Keep the discussion about 4 pages. Build and fix any errors you introduced.`, { label: 'align:disc-ver', phase: 'Align', schema: SCHEMA }),
])
phase('Final')
const fin = await agent(`${CTX}\n\nYou are a FRESH final checker of the whole paper (you did not write any of it). Read the whole PDF text (pdftotext ${P}/main.pdf -) and the sources. Tasks: (1) Consistency: notation, Q-axiom numbering (setting's), 'Question 1/2/3', terminology, statuses and \\src tags, no internal jargon in running text (track IDs like U5/C3/E4, 'the record', 'track single', 'prior C8.3' belong only in \\src or app:ver), consistent restatements of the same result in different places (intro vs sections vs discussion vs app:ver), cross-references that point to the right thing. (2) Fidelity: spot-check the 25 most important claims (abstract, intro answers, main theorems of each section, experiment headline numbers) against the research records (${R}/tracks/*/notes-final.md, prior) and code results (${P}/../code/results/*.md); verify the two fatal fixes (prop:setting:align restriction with rem:setting:alignfail; prop:exp:share with ex:exp:share) are correctly stated everywhere they are used. (3) Presentation: obvious typos, broken sentences, leftover TODO/NOTE comments visible in the PDF, overfull boxes, figures referenced and present, tables legible. Fix what you find directly with minimal edits in any section file (record each change). Then build under the lock and ensure 0 errors, 0 undefined references/citations, 0 multiply defined labels. Write a report to ${RV}/final-check.md. Return changes and anything you could not fix.\n\nAlignment editors' summaries: ${JSON.stringify(align)}`, { label: 'final:check', phase: 'Final', schema: SCHEMA })
return { align, fin }
