

/-! ## T1 §3 (escalation dimension, unstructured classes) -- InfLearn/Unstructured.lean -/

#print axioms InfLearn.Unstructured.chain_not_acc
#print axioms InfLearn.Unstructured.thm_3_2_lower
#print axioms InfLearn.Unstructured.thm_3_2_upper
#print axioms InfLearn.Unstructured.thm_3_2
#print axioms InfLearn.Unstructured.vsVerifier_attains
#print axioms InfLearn.Unstructured.vsVerifier_escCount_le
#print axioms InfLearn.Unstructured.thm_3_9_upper
#print axioms InfLearn.Unstructured.thm_3_9_upper_honest
#print axioms InfLearn.Unstructured.thm_3_9_Esc_le
#print axioms InfLearn.Unstructured.thm_3_9_Esc_le_card
#print axioms InfLearn.Unstructured.elasticChain_length_le
#print axioms InfLearn.Unstructured.thm_3_9_coSingleton_lower
#print axioms InfLearn.Unstructured.exists_honest_prover_coSingleton
#print axioms InfLearn.Unstructured.thm_3_9_coSingleton_forces
#print axioms InfLearn.Unstructured.thm_3_9_coSingleton
#print axioms InfLearn.Unstructured.exists_class_Esc_eq
#print axioms InfLearn.Unstructured.vsVerifier_cost_eq_escCount
#print axioms InfLearn.Unstructured.vsVerifier_escQueries_chain
#print axioms InfLearn.Unstructured.elasticChain_iff
#print axioms InfLearn.Unstructured.Esc_le_worstCost
#print axioms InfLearn.Unstructured.maxEl_le_worstCost
#print axioms InfLearn.Unstructured.worstCost_vsVerifier_le
#print axioms InfLearn.Unstructured.card_coSingleton
#print axioms InfLearn.Unstructured.vsFin_ssubset_of_esc

/-! ## T3 §3-4 (export and certification) -- InfLearn/Export.lean -/

#print axioms InfLearn.Export.invisible_perturbation
#print axioms InfLearn.Export.samples_do_not_determine
#print axioms InfLearn.Export.no_free_export_perturbation
#print axioms InfLearn.Export.exists_poly_interp
#print axioms InfLearn.Export.no_free_export_samples
#print axioms InfLearn.Export.no_free_export_samples_everywhere
#print axioms InfLearn.Export.no_free_export_samples_emb
#print axioms InfLearn.Export.no_free_export_samples_Icc
#print axioms InfLearn.Export.no_free_export_from_samples
#print axioms InfLearn.Export.no_sound_committing_rule
#print axioms InfLearn.Export.nodeClosed_of_addPolyClosed
#print axioms InfLearn.Export.no_free_export_samples_of_poly_subset
#print axioms InfLearn.Export.no_free_export_finite_jet
#print axioms InfLearn.Export.no_free_export_finite_jet'
#print axioms InfLearn.Export.no_free_export_away
#print axioms InfLearn.Export.no_free_export_germ
#print axioms InfLearn.Export.exists_interval_iff_radius_le
#print axioms InfLearn.Export.midrange_sound
#print axioms InfLearn.Export.optimalRule_sound
#print axioms InfLearn.Export.radius_le_of_sound
#print axioms InfLearn.Export.no_interval_of_unbounded
#print axioms InfLearn.Export.coherence_cannot_calibrate
#print axioms InfLearn.Export.coherence_cannot_calibrate_unbounded
#print axioms InfLearn.Export.no_certification_without_regularity
#print axioms InfLearn.Export.lip_cert_sound_point
#print axioms InfLearn.Export.lip_cert_sound_indexed
#print axioms InfLearn.Export.dist_le_iff_sup
#print axioms InfLearn.Export.lip_cert_sound
#print axioms InfLearn.Export.lip_cert_sound_noisy
#print axioms InfLearn.Export.lip_cert_complete_of_net
#print axioms InfLearn.Export.lip_cert_complete
#print axioms InfLearn.Export.lip_cert_complete'
#print axioms InfLearn.Export.lip_lower_bound_of_packing
#print axioms InfLearn.Export.lip_lower_bound_cube
#print axioms InfLearn.Export.lip_lower_bound_cube_adaptive
#print axioms InfLearn.Export.lip_lower_bound_interval
#print axioms InfLearn.Export.lazy_bisection_sound
#print axioms InfLearn.Export.lazy_bisection_miss
#print axioms InfLearn.Export.lazy_bisection_resolution
#print axioms InfLearn.Export.mono_lower_bound
#print axioms InfLearn.Export.mono_lower_bound_ceil
#print axioms InfLearn.Export.abstain_of_line

/-! ## T4 §4 (paradox lower bounds, Thm 4.3(b), Thm 4.4(b),(c)) -- InfLearn/ParadoxLowerBound.lean -/

#print axioms InfLearn.ParadoxLowerBound.forces_of_adversary
#print axioms InfLearn.ParadoxLowerBound.exists_nonSilent_extension
#print axioms InfLearn.ParadoxLowerBound.nonSilent_iff
#print axioms InfLearn.ParadoxLowerBound.exists_feedback_bagBags
#print axioms InfLearn.ParadoxLowerBound.exists_feedback_objBags
#print axioms InfLearn.ParadoxLowerBound.IsValue.unique
#print axioms InfLearn.ParadoxLowerBound.achieves_of_potential
#print axioms InfLearn.ParadoxLowerBound.thm_4_3_b
#print axioms InfLearn.ParadoxLowerBound.thm_4_3_b_eq
#print axioms InfLearn.ParadoxLowerBound.thm_4_4_b_bag_lower
#print axioms InfLearn.ParadoxLowerBound.thm_4_4_b_bag_upper
#print axioms InfLearn.ParadoxLowerBound.thm_4_4_b_bag_value
#print axioms InfLearn.ParadoxLowerBound.thm_4_4_b_unbounded
#print axioms InfLearn.ParadoxLowerBound.thm_4_4_b_obj_lower
#print axioms InfLearn.ParadoxLowerBound.thm_4_4_b_obj_upper
#print axioms InfLearn.ParadoxLowerBound.thm_4_4_b_obj_value
#print axioms InfLearn.ParadoxLowerBound.thm_4_4_b
#print axioms InfLearn.ParadoxLowerBound.chainStep_mem_hypC
#print axioms InfLearn.ParadoxLowerBound.hypC_coherent
#print axioms InfLearn.ParadoxLowerBound.paradox_derivation
#print axioms InfLearn.ParadoxLowerBound.essential_bag
#print axioms InfLearn.ParadoxLowerBound.chainBags_eq
#print axioms InfLearn.ParadoxLowerBound.object_descent
#print axioms InfLearn.ParadoxLowerBound.object_refutes_iff
#print axioms InfLearn.ParadoxLowerBound.exists_object
#print axioms InfLearn.ParadoxLowerBound.exists_feedback_chain
#print axioms InfLearn.ParadoxLowerBound.thm_4_4_c_lower
#print axioms InfLearn.ParadoxLowerBound.thm_4_4_c_upper
#print axioms InfLearn.ParadoxLowerBound.thm_4_4_c_value
#print axioms InfLearn.ParadoxLowerBound.thm_4_4_c_obj_value
#print axioms InfLearn.ParadoxLowerBound.thm_4_4_c
#print axioms InfLearn.ParadoxLowerBound.chainH_eq
#print axioms InfLearn.ParadoxLowerBound.card_class
#print axioms InfLearn.ParadoxLowerBound.SemSound_subset_hypC

/-! ## T5 Thm 2.1(i) (no adaptation with private randomness) -- InfLearn/NoAdaptation.lean -/

#print axioms InfLearn.NoAdaptation.gibbs
#print axioms InfLearn.NoAdaptation.expLoss_eq_sum_marg
#print axioms InfLearn.NoAdaptation.thm_2_1_i
#print axioms InfLearn.NoAdaptation.thm_2_1_i_exists
#print axioms InfLearn.NoAdaptation.thm_2_1_i_maxF
#print axioms InfLearn.NoAdaptation.margHyp_expLoss
#print axioms InfLearn.NoAdaptation.thm_2_1_i_ennreal
#print axioms InfLearn.NoAdaptation.thm_2_1_i_ennreal_maxF
#print axioms InfLearn.NoAdaptation.unifHyp_loss
#print axioms InfLearn.NoAdaptation.unifHyp_supE
#print axioms InfLearn.NoAdaptation.sum_entropy_le_sum_log_card
#print axioms InfLearn.NoAdaptation.sum_entropy_of_uniform
#print axioms InfLearn.NoAdaptation.minimax_of_uniform_marginals
#print axioms InfLearn.NoAdaptation.minimax_of_uniform_marginals_ennreal
#print axioms InfLearn.NoAdaptation.uniform_marginals_of_transitive
#print axioms InfLearn.NoAdaptation.minimax_of_transitive
#print axioms InfLearn.NoAdaptation.Example.no_uniform_marginals
#print axioms InfLearn.NoAdaptation.Example.value_lt_sum_log_card
#print axioms InfLearn.NoAdaptation.Example.sum_entropy_lt
#print axioms InfLearn.NoAdaptation.gibbs_eq
#print axioms InfLearn.NoAdaptation.unifHyp_isProductHyp
#print axioms InfLearn.NoAdaptation.unifHyp_sup'
#print axioms InfLearn.NoAdaptation.margHyp_isProductHyp
#print axioms InfLearn.NoAdaptation.entropy_marg_of_uniform
#print axioms InfLearn.NoAdaptation.unifDist_isDistOn

/-! ## T6 §2 (bilateral completeness, Scott relations) -- InfLearn/Bilateral.lean -/

#print axioms InfLearn.Bilateral.isScott_Th
#print axioms InfLearn.Bilateral.gen_eq_derives
#print axioms InfLearn.Bilateral.exists_maxCoherent
#print axioms InfLearn.Bilateral.thm_2_2_a
#print axioms InfLearn.Bilateral.thm_2_2_a_max
#print axioms InfLearn.Bilateral.thm_2_2_b
#print axioms InfLearn.Bilateral.coherent_iff_realizable
#print axioms InfLearn.Bilateral.cor_2_3
#print axioms InfLearn.Bilateral.cor_2_3_consOp
#print axioms InfLearn.Bilateral.isScott_iff_Th_Val_eq
#print axioms InfLearn.Bilateral.mem_gen_iff
#print axioms InfLearn.Bilateral.Val_Th
#print axioms InfLearn.Bilateral.isClosed_Val
#print axioms InfLearn.Bilateral.scottClosedIso
#print axioms InfLearn.Bilateral.thm_2_6_a
#print axioms InfLearn.Bilateral.thm_2_6_a_closed
#print axioms InfLearn.Bilateral.structural_gen
#print axioms InfLearn.Bilateral.structuralClosedIso
#print axioms InfLearn.Bilateral.thm_2_6_b_validates
#print axioms InfLearn.Bilateral.thm_2_6_b_eq
#print axioms InfLearn.Bilateral.thm_2_6_b_realize
#print axioms InfLearn.Bilateral.cor_2_3_mseq
#print axioms InfLearn.Bilateral.mem_gen_empty
#print axioms InfLearn.Bilateral.Val_gen_TT
#print axioms InfLearn.Bilateral.coherent_TT_iff
#print axioms InfLearn.Bilateral.isScott_sInter
#print axioms InfLearn.Bilateral.isScott_gen
#print axioms InfLearn.Bilateral.gen_subset
#print axioms InfLearn.Bilateral.Coherent.disjoint
#print axioms InfLearn.Bilateral.MaxCoherent.exhaustive
#print axioms InfLearn.Bilateral.MaxCoherent.charFn_mem_Val
#print axioms InfLearn.Bilateral.MaxCoherent.eq_split
#print axioms InfLearn.Bilateral.maxCoherent_of_mem_Val
#print axioms InfLearn.Bilateral.gen_subset_Th_Val
#print axioms InfLearn.Bilateral.Val_gen
#print axioms InfLearn.Bilateral.coherent_gen_iff
#print axioms InfLearn.Bilateral.isScott_iff_exists_Th
#print axioms InfLearn.Bilateral.Th_Val_of_isScott
#print axioms InfLearn.Bilateral.Th_closure
#print axioms InfLearn.Bilateral.Val_Th_of_isClosed
#print axioms InfLearn.Bilateral.Val_subset_Val_iff
#print axioms InfLearn.Bilateral.mem_closure_iff_agree
#print axioms InfLearn.Bilateral.substInvariant_Val
#print axioms InfLearn.Bilateral.structural_Th
#print axioms InfLearn.Bilateral.lindenbaum_interp
#print axioms InfLearn.Bilateral.lindenbaum_validates_iff
#print axioms InfLearn.Bilateral.carnap_Val_eq
#print axioms InfLearn.Bilateral.carnap_mrel_eq

/-! ## T6 Thm 3.4 + Prop 4.7 (Specker) -- InfLearn/Specker.lean -/

#print axioms InfLearn.Specker.not_matchesOn_univ
#print axioms InfLearn.Specker.exists_matchesOn
#print axioms InfLearn.Specker.thm_3_4
#print axioms InfLearn.Specker.thm_3_4_a
#print axioms InfLearn.Specker.thm_3_4_b
#print axioms InfLearn.Specker.thm_3_4_hence
#print axioms InfLearn.Specker.Qk_eq_Pk
#print axioms InfLearn.Specker.exists_prF_eq_Qk
#print axioms InfLearn.Specker.Qk_incoherent
#print axioms InfLearn.Specker.two_atom_coherent
#print axioms InfLearn.Specker.specker_parable
#print axioms InfLearn.Specker.frustrated_triangle
#print axioms InfLearn.Specker.matchesOn_neg
#print axioms InfLearn.Specker.prF_eq_Pk_of_matchesOn
#print axioms InfLearn.Specker.isProb_mixDist_atomCred
