import InfLearn.Prop.Basic
open Finset
#check @Finset.card_le_card_of_injOn
#check @Finset.card_sdiff_add_card_eq_card
#check @Finset.sum_sdiff
#check @Finset.sum_eq_zero_iff_of_nonneg
#check @Finset.sum_boole
#check @Finset.card_le_one
#check @Finset.sum_map
#check @Finset.card_map
#check @Finset.sum_ite_eq
#check @Finset.sum_ite_eq'
#check @div_le_one
#check @Finset.sum_comm
