import InfLearn.StepSoundness
#check @Finset.ssubset_iff_of_subset
#check @List.countP_singleton
#check @List.countP_congr
#check @List.countP_eq_length
#check @Finset.card_image_of_injOn
#check @List.toFinset_card_of_nodup
#check @List.getD_eq_getElem?_getD
#check @List.getElem?_eq_getElem
#check @le_iSup₂_of_le
#check @iInf₂_le
#check @le_iInf₂
#check @List.mem_iff_getElem
#check @List.mem_of_mem_take
#check @Finset.card_erase_of_mem
#check @Finset.length_toList
#check @Finset.nodup_toList
#check @Finset.mem_toList
#check @List.countP_le_length
#check @Finset.card_filter_le
example : (0 : ℕ∞) ≤ 5 := zero_le _
